### ISSUE TITLE
MongoDB Exception – yii\mongodb\Exception

### ISSUE THREAD

**Issue by junezhou** [yiisoft/yii2-mongodb#100]
MongoDB Exception – yii\mongodb\Exception
Failed to connect to: 127.0.0.1:27017: Remote server has closed the connection

http://stackoverflow.com/questions/25261776/mongodb-remote-server-has-closed-the-connection-on-first-connection-after-rest

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |   2.0.7
| PHP version      | 5.5.9
| Operating system | Mac

**Comment by klimov-paul** [comment]
This does not relates to Yii
