### ISSUE TITLE
Issue with findAll(<array of IDs>)

### ISSUE THREAD

**Issue by theOtherNir** [yiisoft/yii2-mongodb#101]
### What steps will reproduce the problem?

$IDs = [
  '111111',
  '222222',
  '333333'
]
unset ($IDs[0]); // leaving the array with keys 1 and 2 which sets the issue ..
$items = Model::findAll($IDs);

### What's expected?
Expecting to get objects 222222 and 333333

### What do you get instead?
Empty result set is returned

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.7
| PHP version      | 5.5.9
| Operating system | Ubuntu server (Amazon SMP)

ps. I've never contributed to Yii's code and not sure that's the correct fix / the core issue lies there but it seems that the issue will be resolved by replacing this row :
`$condition = [$primaryKey[0] => $condition];`
with this : 
`$condition = [$primaryKey[0] => array_values($condition)];`
in file : BaseActiveRecord

Thanks !!

**Comment by klimov-paul** [comment]
Resolved by commit f0e9695c5df213c6fac42e63df43fd8b973ba2c3
