### ISSUE TITLE
php-cli  mongodb memory leak in for loop

### ISSUE THREAD

**Issue by gouchaoer** [yiisoft/yii2-mongodb#103]
### What steps will reproduce the problem?
i need to do mongo tasks as follows, after 12hours the php-cli had used 1.5g memory and failed to go on. i think yii2-mongodb caused the meory leaks, help me!
```php
		/* step:2 */
		$predis = Yii::$app->predis;
		$query=new \yii\mongodb\Query();
		// $id_max=116791286;
		$id_max = 116791286;
		ini_set('memory_limit', - 1);
		// var_dump(ini_get('memory_limit'));
		$predis->set($this->predis_prefix . 'id_max', $id_max);
		$ct=0;
		$per=0;
		for ($i = 0; $i <= $id_max; $i ++)
		{
			$ct++;
			if($ct>$id_max/100)
			{
				$ct=0;
				$per+=1;
				echo ">{$per}\%";
			}
			$one=null;
			$one=$query->from('zhixinginfo')->where(['id'=>$i])->one();
			if($one)
			{
				$predis->hset($this->predis_prefix . 'checked_ids', $i, 1);//2代表该id无结果，1代表有结果
			}
			else
			{
				$predis->sadd($this->predis_prefix . 'unchecked_ids', $i);
			}
		}

```
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |yii2
| PHP version      |5.6
| Operating system |win7  xampp

**Comment by cebe** [comment]
a few questions:

1. what is `Yii::$app->predis`?
2. how is your logging configured?
3. what exactly makes your think it is caused by `yii2-mongodb`?

**Comment by klimov-paul** [comment]
Closed, untill more information arrives.
