### ISSUE TITLE
add offset method

### ISSUE THREAD

**Issue by gouchaoer** [yiisoft/yii2-mongodb#104]
in QueryInterface, you implemented `public function limit($limit);`but forgot `public function offset($offset);`

offset is used in
```
    protected function buildCursor($db = null)
    {
        $cursor = $this->getCollection($db)->find($this->composeCondition(), $this->composeSelectFields());
        if (!empty($this->orderBy)) {
            $cursor->sort($this->composeSort());
        }
        $cursor->limit($this->limit);
        $cursor->skip($this->offset);

        return $cursor;
    }
```
I hacked it as $query->offset=10000 to do the skip job
Hope to override offset method

**Comment by klimov-paul** [comment]
`offset()` method added to the `yii\mongodb\Query` via `yii\db\QueryTrait`:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryTrait.php#L386
