### ISSUE TITLE
YII2 - Mongo:- Unable to add a simple where clause in model query with columns that has integer values.

### ISSUE THREAD

**Issue by avptechnocrats** [yiisoft/yii2-mongodb#105]
### What steps will reproduce the problem?
I have written following line in controller:
$category_details = $category->find()->where(['id'=>$cat_id])->one();
print_r($category_details);
It prints nothing though the collection contains matching record. If I pass hard coded value like 1 or 2 instead of $cat_id in where condition, it fetches the matching category but not with variable. It seems it is adding single/double quote in mongo query. 
However, it works with columns that has string value.

Also, it doesn't work with relations either by hasOne or hasMany. 

Can anyone help me with this ? 
 

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | 5.4
| Operating system | Cent OS

**Comment by klimov-paul** [comment]
@avptechnocrats, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.

**Comment by avptechnocrats** [comment]
Hi Paul,
I posted this query because this is related to the extension "yii2-mongodb" and I think there is any issue with this or need to add any patch for this issue. I would be glad if you can hint me for this issue I am facing here.

Thanks.
