### ISSUE TITLE
YII2 - Mongo:- Unable to add a simple where clause in model query with columns that has integer values. 

### ISSUE THREAD

**Issue by avptechnocrats** [yiisoft/yii2-mongodb#106]
I posted this query because this is related to the extension "yii2-mongodb" and I think there is any issue with this or need to add any patch for this issue. I would be glad if you can hint me for this issue I am facing here.

### What steps will reproduce the problem?
I have written following line in controller:
$category_details = $category->find()->where(['id'=>$cat_id])->one();
print_r($category_details);
It prints nothing though the collection contains matching record. If I pass hard coded value like 1 or 2 instead of $cat_id in where condition, it fetches the matching category but not with variable. It seems it is adding single/double quote in mongo query. 
However, it works with columns that has string value.

Also, it doesn't work with relations either by hasOne or hasMany. 

Can anyone help me with this ? 
 

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | 5.4
| Operating system | Cent OS

**Comment by klimov-paul** [comment]
Duplicates #105

**Comment by klimov-paul** [comment]
OK

Are you able to bypass your problem using raw MongoDB PHP extension, without Yii being involved?

**Comment by avptechnocrats** [comment]
Yes. It works fine without that.

**Comment by klimov-paul** [comment]
Provide this code.

**Comment by avptechnocrats** [comment]
I explained the scenario above. Please let me know what other information you need.

**Comment by klimov-paul** [comment]
You have jsut said you can avoid issue, if you are using raw PHP MongoDB means.
Provide the working code for your selection, staring with row:

```php
$client = new \MongoClient(...);
```

**Comment by avptechnocrats** [comment]
$m = new \MongoClient();
$db = $m->selectDB('esalepoint');
$collection = new \MongoCollection($db, 'categories');

$cursor = $collection->findOne(['_id' => (int)$cat_id]);

**Comment by klimov-paul** [comment]
So?

Compare:

> ['_id' => (int)$cat_id];

with:

> ['id'=>$cat_id]

Does not seems equal to me.

**Comment by klimov-paul** [comment]
Are you claiming that following code does not work:

```php
$category_details = $category->find()->where(['id'=>(int)$cat_id])->one();
```

?

**Comment by avptechnocrats** [comment]
Why do I need to type cast here into integer? It's causing problems with
the relations. How can I typecast that in relations? Please suggest.

**Comment by klimov-paul** [comment]
Sorry, I have wasted enough time here, educating you.
As I already said: use forum for the help.

**Comment by avptechnocrats** [comment]
These stuffs are not mentioned anywhere in WIki or any other documentation.
That's why I needed to post it here. My sincere apologies for this though.

**Comment by klimov-paul** [comment]
Have not we just find out that no typecast is performed by MongoDB driver by default?
Here is **your** code:

```php
$cursor = $collection->findOne(['_id' => (int)$cat_id]);
```

Here is a doc block, which says 'yii2-mongodb' uses MongoDB PHP Extension:
https://github.com/yiisoft/yii2-mongodb#installation

And now you are blaming me, that MongoDB PHP Extension does not typecast some abstract value to the integer.
I can see no reason to copy-paste the entire documentation from php.net about MongoDB PHP Extension.

If you are concerned about this behavior - report it to php.net
