### ISSUE TITLE
Mongodb connection process too much

### ISSUE THREAD

**Issue by soyaf518** [yiisoft/yii2-mongodb#107]
### What steps will reproduce the problem?
When I refer to mongodb Yii extensions, and connect to the mongodb database.I found on the server mongodb connection is not automatically shut down, leading to the emergence of thousands of mongodb connection process on the server.

MongoDB1.3 version of the above are connected through the MongoClient class, the default is a long connection, and can not be modified.We need to call the close method of mongoClient to close the mongodb connection.Such as, $mongo = new MongoClient('mongodb://localhost:27017'), we can do like this: $mongo->close() or $mongo->close(true).

I think we should join the destructor in the yii2-mongodb/Collection.php file. And I tested it and made sure that would work.
<pre>
publuc function __destruct()
{
    if ($this->mongoClient !== null) {
        $this->mongoClient->close();
   }
}
</pre>

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.4
| PHP version      | 5.6.9
| Operating system | centos

**Comment by klimov-paul** [comment]
According to the php.net `close()` method should not be invoked in general:
http://php.net/manual/en/mongoclient.close.php

> The MongoClient::close() method forcefully closes a connection to the database, even if persistent connections are being used. You should never have to do this under normal circumstances. 


> Since version 1.2.0 this is no longer the case and it is a bad idea to call close as you might end up overloading the server with connections under high load.

**Comment by soyaf518** [comment]
That we do not need to call the close method is called frequently cause high server load. Thank you very much.
