### ISSUE TITLE
Error deleting from Mongo database

### ISSUE THREAD

**Issue by lefteyecc-pu** [yiisoft/yii2-mongodb#108]
### What steps will reproduce the problem?
Attempt to delete documents based on ids through a collection:

``` 
(new yii2-mongodb\Collection)->remove([
    id => [
        1, 2, 3 ,4 ,5
    ]
]);
```
### What's expected?

The delete operation to work properly.

### What do you get instead?

```
Exception 'yii\mongodb\Exception' with message 'Unable to cast object of type 'MongoDB.Bson.BsonDocument' to type 'MongoDB.Bson.BsonBoolean'.'

in /var/www/api.pickledup.com/vendor/yiisoft/yii2-mongodb/Collection.php:546

Stack trace:
#0 /var/www/api.pickledup.com/vendor/yiisoft/yii2-mongodb/ActiveRecord.php(92): yii\mongodb\Collection->remove(Array, Array)
#1 /var/www/api.pickledup.com/vendor/mhdevnet/yii2-search/IndexerMongo.php(287): yii\mongodb\ActiveRecord::deleteAll(Array)
````

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.4
| PHP version      | 7.0
| Operating system | Ubuntu

**Comment by klimov-paul** [comment]
Unable to reproduce.
Extra unit test added to verify this: f62e782cc58486ddef16d6207d515db173a453c9
