### ISSUE TITLE
yii\mongodb\Exception contains non utf-8 character

### ISSUE THREAD

**Issue by gouchaoer** [yiisoft/yii2-mongodb#114]
### What steps will reproduce the problem?
in chinese win7, if mongo is unavailable
### What do you get instead?
 yii\mongodb\Exception:Failed to connect to: 192.168.2.106:27018: 
 �������ӷ���һ��ʱ���û����ȷ�𸴻����ӵ�����û�з�Ӧ�����ӳ���ʧ�ܡ�

i need to encode the  yii\mongodb\Exception message into json, but the string contains non utf-8 character. change it into utf-8.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |2.1
| Yii MongoDB version    |newest
| MongoDB server version |no mongodb
| PHP version            |5.6
| Operating system       |win7, XAMPP

**Comment by klimov-paul** [comment]
Yii does not perfrom any encoding conversion for the Exception messages they are return as they are.
If you need a specific representation for it - you should handle it yourself.
