### ISSUE TITLE
Prepare 2.1 Release

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii2-mongodb#119]
Checklist for 2.1 release:

- [x] Resolve TODOs
- [x] Update DocComments
- [x] Update Guide
- [x] Better UPGRADE notes
- [x] Simplify Travis installation (see https://github.com/travis-ci/travis-ci/issues/3694#issuecomment-155186560)

Help is appreciated.

**Comment by klimov-paul** [comment]
Guide updated.
@softark, can you handle recent changes at the guide for Japanese?

**Comment by klimov-paul** [comment]
Complete

**Comment by softark** [comment]
@klimov-paul, OK, I'll update the translation in a day or two.
