### ISSUE TITLE
Model returned has dates as MongoDB\BSON\UTCDateTime not \MongoDate

### ISSUE THREAD

**Issue by nigelterry** [yiisoft/yii2-mongodb#124]
My application works with PHP 5.6 and the released version of yii2-mongodb. It also works with PHP 7.0 and mongofill/mongofill. I've just tested with the new dev 2.1.0 version and it fails.

The released version returns a model instance with dates as \MongoDate object. The new version returns dates as \MongoDB\BSON\UTCDateTime object. \MongoDate has a sec property which I use extensively in views. \MongoDB\BSON\UTCDateTime only has a property milliseconds.

Is this by design, because it causes backward compatibility issues?

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/UPGRADE.md#upgrade-from-yii-205

**Comment by klimov-paul** [comment]
You may use `UTCDateTime::toDateTime()` in order to receive a `\DateTime` instance and then get the seconds from it.
