### ISSUE TITLE
$elemMatch in Projection

### ISSUE THREAD

**Issue by Meabed** [yiisoft/yii2-mongodb#128]
### Projection converted to boolean line below 
[Commit](https://github.com/yiisoft/yii2-mongodb/blob/1717d7d1f023a1b32851fcc41dd66b56aef723f8/QueryBuilder.php#L367)
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.8
| Yii MongoDB version    | master
| MongoDB server version | php-mongodb
| PHP version            | php7
| Operating system       | Ubuntu

**Comment by klimov-paul** [comment]
Resolved by commit a76fa46076e913bb047e675412932f8122109fd0
