### ISSUE TITLE
Apply rules to unselected field in query

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2-mongodb#129]
### What steps will reproduce the problem?

In the model rules

```php
public function rules() {
    return [
        [['status', 'status', 'count'], 'filter', 'filter' => function($value){
            return (int)$value;
        }],
    ];
}
```

and for save just name in model

```php
$model = Model()->find()->select(['_id', 'name'])->one();
$model->name = 'test'
$model->save();
```

### What's expected?

Just save name and not manipulate other fields.

### What do you get instead?

Before in the version ext-mongo it's work and just changes affect to selected field but in new one also apply to rules field and make all of it `0`.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | dev-master
| Yii MongoDB version    | dev-master
| MongoDB server version | 3.2
| PHP version            | 5.6
| Operating system       | Ubuntu 14.04

**Comment by klimov-paul** [comment]
> Before in the version ext-mongo it's work

Unable to reproduce with tag 2.0.5.
Unit test:

```php
public function testIssue129()
    {
        $record = new Customer;
        $record->name = 'new name';
        $record->email = 'new email';
        $record->address = 'new address';
        $record->status = 7;
        $record->file_id = 10;
        $record->save();

        $model = Customer::find()->select(['_id', 'name'])->one();
        $model->name = 'test';
        $model->save();

        $record = Customer::find()->one();
        $this->assertEquals(7, $record->status);
    }
```

Fails:

```
There was 1 failure:

1) yiiunit\extensions\mongodb\ActiveRecordTest::testUpdate2
Failed asserting that 0 matches expected 7.
```

> apply to rules field and make all of it 0.

This is expected behavior. You should avoid validation of not selected fields ot make it work as you describe:

```php
$model = Model()::find()->select(['_id', 'name'])->one();
$model->name = 'test';
$model->validate(['name']);
$model->save(false);
```
