### ISSUE TITLE
Serialization of 'MongoDB\BSON\ObjectID' is not allowed 

### ISSUE THREAD

**Issue by cuongbn** [yiisoft/yii2-mongodb#132]
I'm use: yiisoft/yii2-mongodb ~2.1.0 -> satisfiable by yiisoft/yii2-mongodb[2.1.x-dev]
php 7.0.7 64 bit with library mongodb 1.1.7

When i set cache, value has object(MongoDB\BSON\ObjectID), it error :"Serialization of 'MongoDB\BSON\ObjectID' is not allowed"

Please, How can i fix it?

**Comment by klimov-paul** [comment]
https://github.com/mongodb/mongo-php-driver/issues/270
