### ISSUE TITLE
New driver issues with buildCondition() missing from Collection.php

### ISSUE THREAD

**Issue by tahpot** [yiisoft/yii2-mongodb#134]
What happened to buildCondition() support when the codebase was upgraded to use the MongoDB driver?

Our whole application makes use of buildHashConditions, buildInConditions etc, but that appears to have been completely removed in the upgrade.

Is this no longer supported?

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.7
| Yii MongoDB version    | 2.1.0
| MongoDB server version | 3.x
| PHP version            | 5.5
| Operating system       | Linux

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/UPGRADE.md#upgrade-from-yii-205

**Comment by tahpot** [comment]
Thanks.

I was looking at the change log, which mentioned changing the mongo extension in use, but didn't highlight the significant method signature changes.

The documentation of Collection.php and Query.php still reference the old code.

**Comment by cebe** [comment]
as far as I see the docs are up to date: http://www.yiiframework.com/doc-2.0/yii-mongodb-collection.html which document are you referring to?

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/yii-mongodb-query.html#batch%28%29-detail says "available since version 2.1"

**Comment by tahpot** [comment]
Ah yes, Query is okay, however Collection.php mentions buildCondition():

> print_r($collection->buildCondition($condition));

And the last sentence references \MongoId

**Comment by klimov-paul** [comment]
It is incorrect PHP docs - I have miss it. Will be fixed soon.

**Comment by klimov-paul** [comment]
2babe1b6875209ffc7395fac3984821623883c49
