### ISSUE TITLE
hello,why when i am install this ext,it's warn me requires ext-mongodb > 1.0.0 and i has install the driver

### ISSUE THREAD

**Issue by smartyPHP** [yiisoft/yii2-mongodb#135]
### What steps will reproduce the problem?
hello,why when i am install this ext,it's warn me requires ext-mongodb > 1.0.0 and i has install the driver
### What's expected?
i has install ext-mongodb and `php -m` will display mongo
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
@smartyPHP, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
