### ISSUE TITLE
There has no function buildCondition in class Collection on version 2.1.*

### ISSUE THREAD

**Issue by lizishushu** [yiisoft/yii2-mongodb#137]
### What steps will reproduce the problem?

There has no function buildCondition in class Collection on version 2.1.*

### What's expected?

In the version of 2.0.* I can use the function buildCondition to built query  with use REGEX .But in new version of mongo extension , the function has remove .

### What do you get instead?

What should i do when i use the latest extension version?

The below is my code :
___________

                $word = 'test';
				$collection = Yii::$app->mongodb->getCollection ( 'connection' );
				$condition = [ 
						'REGEX',
						'line',
						'/^'.$word .'/' 
				];
				$collection->buildCondition ( $condition );

___________

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.7
| Yii MongoDB version    | 2.1
| MongoDB server version | 3.2
| PHP version            | 7
| Operating system       |centos 7

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/UPGRADE.md#upgrade-from-yii-205

> Command and query composition methods at \yii\mongodb\Collection, such as buildCondition(), ensureMongoId() and so on, have been removed. Use \yii\mongodb\QueryBuilder methods instead.
