### ISSUE TITLE
Yii MongoDB ''auth fails""

### ISSUE THREAD

**Issue by AlexJapson** [yiisoft/yii2-mongodb#138]
#### I can't connection to mongodb from yii2 

When i want use gii with mongo i have exception 
![image](https://cloud.githubusercontent.com/assets/5379312/16686419/74305fbc-452b-11e6-95bd-5124240df5a6.png)

#### In nginx error.log
``` log
2016/07/08 15:12:11 [error] 24438#0: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'MongoDB\Driver\Manager' not found in /home/alexey/www/vendor/yiisoft/yii2-mongodb/Connection.php on line 355" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /gii1/default/view?id=mongoDbModel HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost", referrer: "http://localhost/gii1"
```

#### In web.php
``` php
'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://localhost:27017/admin'
        ],
```

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.8
| Yii MongoDB version    | 2.1
| MongoDB server version | 3.2
| PHP version            | 5.5.9
| Operating system       | Ubuntu 14.04

**Comment by klimov-paul** [comment]
Are you able to connect your database from other client?

**Comment by AlexJapson** [comment]
I can connect with db  from MongoChef, when i add 'defaultDatabaseName' i have next exception
![image](https://cloud.githubusercontent.com/assets/5379312/16686754/b610e580-452d-11e6-94ee-d686ea69688f.png)

**Comment by klimov-paul** [comment]
> I can connect with db from MongoChef

Without username and password?

**Comment by AlexJapson** [comment]
No, i have remote mongodb on my server, and i connecting `mongodb://root:mypass@mysite:27017/admin`

**Comment by klimov-paul** [comment]
Then why your `dsn` does not contain it?

**Comment by klimov-paul** [comment]
I am closing this as incorrect usage.
