### ISSUE TITLE
There is an error when I use php7 

### ISSUE THREAD

**Issue by leaxoy** [yiisoft/yii2-mongodb#139]
When use yii2, yii2-mongodb, php7.0.7 and mongodb 3.2.6, I meet this error.

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.9-dev
| Yii MongoDB version    |2.1.0
| MongoDB server version |3.2.6
| PHP version            |7.0.7
| Operating system       |OS X 10.11 Ubuntu 15.10

**Comment by leaxoy** [comment]
Error

Class 'MongoDB\Driver\Query' not found
1. in /home/cherub/HomeRoot/adminjobfair/vendor/yiisoft/yii2-mongodb/Command.php at line 286
277278279280281282283284285286287288289290291292293294295 
        $readConcern = $this->getReadConcern();
        if ($readConcern !== null) {
            $options['readConcern'] = $readConcern;
        }
 
        try {
            $this->beginProfile($token, __METHOD__);
 
            $query = new \MongoDB\Driver\Query($this->document, $options);
            $this->db->open();
            $server = $this->db->manager->selectServer($this->getReadPreference());
            $cursor = $server->executeQuery($databaseName . '.' . $collectionName, $query);
            $cursor->setTypeMap($this->db->typeMap);
 
            $this->endProfile($token, __METHOD__);
        } catch (RuntimeException $e) {
            $this->endProfile($token, __METHOD__);
            throw new Exception($e->getMessage(), $e->getCode(), $e);

**Comment by jasonwestshell** [comment]
yii2 and mongoDB 3.0, I used this :""mongodb/mongodb": "^1.0.0"" .
This line is composer.json file ,you can try it

**Comment by jasonwestshell** [comment]
try this https://github.com/mongodb/mongo-php-library

**Comment by klimov-paul** [comment]
Obviously you do not have `mongodb` PHP extension installed.
http://us1.php.net/manual/en/set.mongodb.php

**Comment by leaxoy** [comment]
Y, maybe it caused by old version of mongodb used by my teammate.  I will be feedback after new test finished. 😂

**Comment by TbhT** [comment]
i have met  the same problem, but i had installed the mongodb php extension, and the OS is **Ubuntu16.04** 

```bash
$ php -m & php -v
...
mongodb
...

PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```
what it happens ? and when i switch **php5** , the error will not appear.

@klimov-paul  

and i made a test with this link below
[php.net/mongo](http://us1.php.net/manual/en/class.mongodb-driver-query.php).

and it result
```bash
stdClass Object
(
    [id] => 2
    [name] => Name 2
)
```
it was also prove that i had installed the php-mongodb-extension  .

The env is **php7**,     "yiisoft/yii2": ">=2.0.5",     "yiisoft/yii2-mongodb": "^2.0",

thanks a lot.

**Comment by klimov-paul** [comment]
Check you PHP 7 environment, make sure correct extension is intalled and included into `php.ini`.
There is nothing else I can do for you.

**Comment by TbhT** [comment]
I solved the problem, and it was because of my environment which only **CLI** not **APACHE2** . 

Thank your advice a lot  .

:p
