### ISSUE TITLE
Can't Login with new Driver

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2-mongodb#140]
### What steps will reproduce the problem?
Logging in.
### What's expected?
User gets logged in.
### What do you get instead?
User was not logged in.
### Additional info
I have an web application that had a working login on the old MongoDB ext  and PHP 5.x.x. 
I updated to the new MongoDB extension and PHP 7. 
The login no longer works on my application. 

I also installed a default advanced app and was able to login via MySQL and PHP 7.  I switched it to MongoDB and I couldn't login.  I don't think it's setting the session vars right.

The debug panel does not show a post request when trying to log in however if you dump the Yii post()  it shows the username and password that was sent. 

When you login with the wrong credentials it shows a post in the logs.

When you use the correct credentials it just resets the form.  It also finds the user and sets it... just not logging them in.  There are also no validation errors.

It creates the session however, it's not putting any data in it when attempting to login.  I can also create anything in the application so the connection works fine just not the actual logging in. 

Everything above happens on both mine and the default one.  They behave exactly the same. I will continue to try and track the issue down.  Please let me know if you need anymore information. 

| Q                      | A
| ---------------------- | ---
| Yii version            |2.0.7/2.0.8/2.0.9/2.0.10
| Yii MongoDB version    |2.0.1/ *
| MongoDB server version |3.2.0
| PHP version            |7.0.6
| Operating system       |Windows 10

**Comment by klimov-paul** [comment]
Caused by #132

**Comment by klimov-paul** [comment]
In order to bypass this problem you should convert `ObjectID` into a string at `Identity::getId()` method:

```php
class Identity extends ActiveRecord implements IdentityInterface
{
    public function getId()
    {
        return $this->getPrimaryKey()->__toString();
    }
   // ...
}
```
