### ISSUE TITLE
MongoDbMessageSource builds wrong messages array

### ISSUE THREAD

**Issue by kudzuu** [yiisoft/yii2-mongodb#141]
### What steps will reproduce the problem?
Configure yii2-advanced template for i18n translations:
`
'language' => 'th',
 'sourceLanguage' => 'en-US',
'i18n' => [
            'translations' => [
                'app' => [
                    'class' => 'yii\mongodb\i18n\MongoDbMessageSource',
                ],                
            ],
        ],

mongo collection:
{ 
    "_id" : ObjectId("57a96d25c02fdb1991def59e"), 
    "category" : "app", 
    "language" : "th", 
    "messages" : [
        {
            "Recommended" : "Hallo Welt!"
        }
    ]
}

somewhere in the view:
\yii\base\Event::on(\yii\i18n\MessageSource::className(), \yii\i18n\MessageSource::EVENT_MISSING_TRANSLATION, function ($event) {
               Yii::trace(get_class($event->sender));
            });
`

### What's expected?
Yii::t('app', 'Recommended') --  "Hallo Welt!"

### What do you get instead?
EVENT_MISSING_TRANSLATION

### Additional info

Default PhpMessageSources works fine. MySQL defined message sources works fine.

Problem in structure of array. Look at MessageSource.php line 109.

**Comment by kudzuu** [comment]
Just need to make $messages array flat.

**Comment by klimov-paul** [comment]
Unable to reproduce: `MongoDbMessageSource` works fine.
There is a unit test, which verifies it:
https://github.com/yiisoft/yii2-mongodb/blob/master/tests/i18n/MongoDbMessageSourceTest.php

**Comment by klimov-paul** [comment]
I assume you get event handler trigger from some other message source since you bind your event handler to the base `yii\i18n\MessageSource`.

**Comment by kudzuu** [comment]
Sorry, for blaming source code, problem in documentation. I took collection example from http://www.yiiframework.com/doc-2.0/yii-mongodb-i18n-mongodbmessagesource.html

correct example for schema example should be:

`{ 
    "language" : "th", 
    "category" : "app", 
    "messages" : {
        "Recommended" : "แนะนำโดย"
       ...
    }
}`

**Comment by klimov-paul** [comment]
fe0f2b0f10714fb528f98ba800646e4f78ef522e

**Comment by samdark** [comment]
@kudzuu thanks!
