### ISSUE TITLE
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: columns'

### ISSUE THREAD

**Issue by KostyaChoporov** [yiisoft/yii2-mongodb#142]
### What steps will reproduce the problem?
use CreateIndexes in migration class
### What's expected?
create indexes
### What do you get instead?

PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: columns'

in /Users/kostya/www/slots_yii/vendor/yiisoft/yii2-mongodb/Migration.php:93

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |  2.0.9
| Yii MongoDB version    | 2.1.0
| MongoDB server version | 3.2.8
| PHP version            | 5.6.24
| Operating system       | OS X 10.11.3

Problem with this method https://github.com/yiisoft/yii2-mongodb/blob/master/Migration.php#L93
$columns not defined. Looks like copy-paste from createIndex method

**Comment by klimov-paul** [comment]
Resolved by commit 6a91fb5daf176e9b870fee75be2d6793c91af105
