### ISSUE TITLE
Join retry mechanism in connection

### ISSUE THREAD

**Issue by xiaoxing598** [yiisoft/yii2-mongodb#143]
A recent project using the cloud database, which is the address of the load, so the connection may be connected to failure, the other party to my proposal is to join the database to join the retrial, the sample code is as follows:

```
$maxRetries = 5;
                for ($counts = 1; $counts <= $maxRetries; $counts++) {
                    try {
                        $this->mongoClient = new \MongoClient($this->dsn, $options);
                    } catch (\Exception $e) {
                        continue;
                    }
                    break;
}
```

I hope the authorities will be able to integrate this feature

**Comment by klimov-paul** [comment]
Feature rejected: it is not general enough and can be easily implemented at particular project level.
