### ISSUE TITLE
How to use 'andFilterWhere' with 'like' for integer fields in Yii2?

### ISSUE THREAD

**Issue by andreyshade** [yiisoft/yii2-mongodb#144]
I try to make a filter for integer field in mongoDB using andFilterWhere.

`$query->andFilterWhere(['like', 'code', $this->code ]);`

This method work fine for String value but for integer value doesn't work. How to use this method for integer fields?

**Comment by samdark** [comment]
How should "LIKE" work for ints?

**Comment by andreyshade** [comment]
I have int fields in mongoDB, for example: 10012345678, 1321005687, 134567989. 
If I find 100, result should be 10012345678, 1321005687

**Comment by klimov-paul** [comment]
@andreyshade, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
