### ISSUE TITLE
`yii\mongodb\Query::exists()` always returning true

### ISSUE THREAD

**Issue by urmaul** [yiisoft/yii2-mongodb#150]
### What steps will reproduce the problem?
Try to execute `exists()` method on query that finds nothing.

### What's expected?
Result is false.

### What do you get instead?
Result is true.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | --
| Yii MongoDB version    | 2.1.1
| MongoDB server version | 3.2.8
| PHP version            | 5.5.9
| Operating system       | Linux Mint 17.2 Rafaela

**Comment by klimov-paul** [comment]
Resolved by commit dc19a5ea7b41afd2810fea9c73db13d20e751903
