### ISSUE TITLE
To use the TTL index instead of the GC

### ISSUE THREAD

**Issue by romeOz** [yiisoft/yii2-mongodb#16]
How about to use [TTL index](http://docs.mongodb.org/manual/tutorial/expire-data/) instead of [GC](https://github.com/yiisoft/yii2-mongodb/blob/master/Session.php#L187-L193)

**Comment by klimov-paul** [comment]
This is require session collection to always precreated, which developer may forget about.
Still, TTL usage for GC may be used as an option here, you are free to create a PR if you pleased.

**Comment by klimov-paul** [comment]
No changes are need for this feature implementation: if you have setup TTL index for the session collection, you can always disable GC via `Session::gCProbability`.

Docs added:
88741aa476ac4bcf843c1e9e7c767d48b91ce9e9
