### ISSUE TITLE
MongoDbManager не реализовывает абстрактный метод BaseManager?

### ISSUE THREAD

**Issue by iarchvile** [yiisoft/yii2-mongodb#163]
При попытке выполнить`php yii rbac/init` вылетает ошибка

`PHP Fatal error:  Class yii\mongodb\rbac\MongoDbManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (yii\rbac\ManagerInterface::getChildRoles) in yiisoft\yii2-mongodb\rbac\MongoDbManager.php on line 38`

"yiisoft/yii2-mongodb": "2.1.1" 

```
 'authManager' => [
            'class' => 'yii\mongodb\rbac\MongoDbManager',
            'defaultRoles' => ['admin', 'expert', 'member'],
        ],
```

Скопировал getChildRoles из DbManager, всё заработало

**Comment by samdark** [comment]
Уже исправлено в https://github.com/yiisoft/yii2-mongodb/commit/89ea4bee51590aea0d8eb26b75e234e63938f5be. Будет в следующем релизе.
