### ISSUE TITLE
Debug panel show one query (fetch cursor id = 0)

### ISSUE THREAD

**Issue by skworden** [yiisoft/yii2-mongodb#167]
Still shows the fetch cursor id = 0 in the debug panel.

https://github.com/yiisoft/yii2-mongodb/issues/126

| Q                      | A
| ---------------------- | ---
| Yii version            |  2.0.11 dev
| Yii MongoDB version    | 2.1.2
| MongoDB server version | 3.2.7
| PHP version            |7.0.1
| Operating system       | Windows 10

**Comment by klimov-paul** [comment]
This is expected.
There are always 2 log entires per each mongo query: one for the find command the second - for the cursor fetching.

![mongo-debug](https://cloud.githubusercontent.com/assets/1482054/20174557/013d6de6-a747-11e6-88ef-7bdd09d964a4.JPG)

I can see no issue here.
