### ISSUE TITLE
Update queries can create records by default

### ISSUE THREAD

**Issue by urmaul** [yiisoft/yii2-mongodb#168]
### What steps will reproduce the problem?
Run "update" query with condition that passes no records.

### What's expected?
Nothing happens.

### What do you get instead?
New record created with fields you wanted to update.

### Additional info
That's because in yii2 "upsert" option is true by default: https://github.com/yiisoft/yii2-mongodb/blob/4c809b59d640d083fcb39431e3087780fdb4f895/Command.php#L448
And that's confusing because of:
- it's not the behavior you expect
- in MongoDB this option is false by default: https://docs.mongodb.com/v3.2/reference/method/db.collection.update/

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.10
| Yii MongoDB version    | 2.1.2
| MongoDB server version | 3.2.10
| PHP version            | 7.0.12
| Operating system       | Linux Mint 17.2 Rafaela

**Comment by klimov-paul** [comment]
This is expected behavior - it make extension consistent with the regular DB.
You can specify `upsert` option to any value yourself if needed.

**Comment by urmaul** [comment]
In which regular DB update query inserts rows by default?

**Comment by klimov-paul** [comment]
Resolved by commit a86e92433c823df9c3030e169d77980379653cd5
Thanks for reporting.
