### ISSUE TITLE
ActiveQuery `count()` returns wrong value

### ISSUE THREAD

**Issue by tuyakhov** [yiisoft/yii2-mongodb#173]
### What steps will reproduce the problem?
The problem is that ActiveDataProvider returns wrong `totalCount` number. 
For example:
```
// given that the customer has 10 orders and there are 100 orders in database in general.
        $customer = Customer::findOne(['status' => 1]);
        $provider = new ActiveDataProvider([
            'query' => $customer->getOrders(),
        ]);
```
`$provider->getTotalCount()` will return 100 instead of 10, although `$provider->getModels()` has right number of records(10).
### What's expected?
`$provider->getTotalCount()` to return 10
### What do you get instead?
100

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.11-dev
| Yii MongoDB version    | dev-master
| MongoDB server version | 3.2.6
| PHP version            | 7.1.0RC6
| Operating system       | macOS Sierra

**Comment by klimov-paul** [comment]
Resolved by commit d7cfcf42f49928e6b480965069c213853f03e363
