### ISSUE TITLE
sum,average,min,max should return 'null' rather than '0'  if no result matching

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-mongodb#178]
### What steps will reproduce the problem?

in case you have a collection like 'orders' and you want to collect the sum of the 'total' but no rows matching the conditions
ex:

 Order::find()->where(['field'=>'Value'])->sum();
 Order::find()->where(['field'=>'Value'])->average();
 Order::find()->where(['field'=>'Value'])->max();
 Order::find()->where(['field'=>'Value'])->min();

### What's expected?
I'm expecting always to return int but it's return null
### What do you get instead?
i'm getting null

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
This is expected behavior. E.g. querying max value from the empty list produces an empty value.

**Comment by devypt** [comment]
@klimov-paul check this
https://docs.mongodb.com/manual/reference/operator/aggregation/sum/
from mongo documentation



Example	Field Values	Results
{ $sum : <field> }	Numeric	Sum of Values
{ $sum : <field> }	Numeric and Non-Numeric	Sum of Numeric Values
{ $sum : <field> }	Non-Numeric or Non-Existent	0

**Comment by devypt** [comment]
http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_sum
behavior is diffrent in mysql which will return null in no rows found

**Comment by klimov-paul** [comment]
You do not read the docs carefully.
Here is quote from your link:

> If used on a field that does not exist in any document in the collection, $sum returns 0 for that field.

`$sum` will return `o` if you use it over non-existing field, but over several records:

```
Order::find()->sum('non_existing_field');
```

PHP code does not changes the default MongoDB behavior anyhow, see
https://github.com/yiisoft/yii2-mongodb/blob/master/Query.php#L596

The aggregation result is returned as it is from the driver.
If you have further concerns about this behavior - you should report it to php.net

**Comment by devypt** [comment]
@klimov-paul clear, Thank you.
