### ISSUE TITLE
ObjectID in init() of Upload.php

### ISSUE THREAD

**Issue by KasselR** [yiisoft/yii2-mongodb#179]
When i save an document with an existing MongoID i will get an
Error: Call to undefined function yii\mongodb\file\ObjectID() in Upload.php Line 107.

Upload.php Line 107: $this->documentId = $this->document['_id'] instanceof ObjectID ? $this->document['_id'] : ObjectID($this->document['_id']); 

Solution: 
change Line 107 as follow:
 $this->documentId = $this->document['_id'] instanceof ObjectID ? $this->document['_id'] : new ObjectID($this->document['_id']); 

If i use an custom generated id, like a Date oder something else(*), it will change the id to an MongoDB\BSON\ObjectID and i get an Error: 
Exception 'MongoDB\Driver\Exception\InvalidArgumentException' with message 'Error parsing ObjectID string: xxxxxx
in this case we need to change the Line 107 as follow:
$this->documentId = $this->document['_id']

(*) for BigData storing inside Mongo we customice the internal Mongoid to an string like this:
ID:STRING:MICROSECONDS

Maybe i need to override the init Method inside application. But how?

**Comment by klimov-paul** [comment]
Resolved by commit 80c54ada648d5b8e20a6d2c8aa8ef49f401274a1
