### ISSUE TITLE
composer installation decency issue , not detecting my mongo db php ext 1.6.6 

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-mongodb#18]
I tried to install the yii2 mongo ext but it's says

     yiisoft/yii2-mongodb 2.0.x-dev requires ext-mongo >=1.5.0 -> the requested  PHP extension mongo is missing from your system

while i already installed the php ext version 1.6.6 (latest one).

I checked phpinfo() and i can see that the extension i installed .

**Comment by klimov-paul** [comment]
This sounds like a composer issue.

**Comment by doctoruna** [comment]
Thanks for fast replay, I manged to solve it, actually mongodb extension was showing to be installed in phpinfo() by not with php -m .

I just run 

    echo "extension=mongo.so" >> /etc/php5/cli/php.ini

**Comment by devypt** [comment]
Thanks for fast reply, I manged to solve it, actually mongodb extension was showing to be installed in phpinfo() by not with php -m .

I just run

    echo "extension=mongo.so" >> /etc/php5/cli/php.ini
