### ISSUE TITLE
Calling unknown method: yii\mongodb\ActiveQuery::createCommand()

### ISSUE THREAD

**Issue by EsoftsLimited** [yiisoft/yii2-mongodb#180]
### What steps will reproduce the problem?
On saving/update a model at unique validation
### What's expected?
validate uniqueness of a row before inserting
### What do you get instead?
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: yii\mongodb\ActiveQuery::createCommand()

### Additional info
validation rukes are as follow
`[['content'],'unique','targetAttribute'=>['content','created_by'],'message'=>'Seem you already a contact with this email address'],
          [['guid'],'unique','targetAttribute'=>['guid','created_by'],'message'=>'Seem you already a contact`

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
Please provide full error stack-trace

**Comment by cebe** [comment]
@klimov-paul it is a BC break in framework code, see https://github.com/yiisoft/yii2/issues/13485

**Comment by klimov-paul** [comment]
I see.
The issue will tracked at  yiisoft/yii2#13485 then.
