### ISSUE TITLE
\MongoDB\BSON\UTCDateTime Sorting and Other conditions

### ISSUE THREAD

**Issue by EsoftsLimited** [yiisoft/yii2-mongodb#181]
### What steps will reproduce the problem?
When i try to sort a column of type \MongoDB\BSON\UTCDateTime in yii2 two nothing happen
`
$query = self::find();
        
        // add conditions that should always apply here
        $query->orderBy(['created_at'=>SORT_ASC]);
`
Other issue i have on the same field is applying between condition to get records between dates
`
$finder = self::find();
         $finder->where(['between', 'created_at',
            strtotime('first day of this month'),
            strtotime('last day of this month')]);
`

### What's expected?
I expect rows to be ordered in ascending or descending level
### What do you get instead?
No effects

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |2.x
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
Sort is covered by unit tests:
https://github.com/yiisoft/yii2-mongodb/blob/master/tests/QueryRunTest.php#L193-L208

This extension does not process sorting for `UTCDateTime` fields in any special way.
If you sure you there is no problem in your own code, you should report this issue to mongodb.org or php.net

**Comment by EsoftsLimited** [comment]
When  i query using MongoShell  with the following command it works well
`db.collectionName.find({"created_at":{"$gte":ISODate("2017-02-01T15:29:30.439+0000"),"$lte":ISODate("2017-02-01T15:29:31.439+0000")},"type":"vaccinated"})
`
When i use Yii Query the following is generated
`
animal_db.command({"count":"animals","query":{"$and":[{"created_at":{"$gte":"MongoDB\\BSON\\UTCDateTime(1485896399)","$lte":"MongoDB\\BSON\\UTCDateTime(1485964152)"}},{"type":"vaccinated"}]}})

`
The above doesn't return any values
The query Command i have used is
`
$args=['created_at'=>['$gte'=>to_date($startDay),'$lte'=>to_date($endDay)]];
       
$finder->where($args);
`
While the function i used to insert the dates is 
`
function to_date($timestamp)
{
  
 return new \MongoDB\BSON\UTCDateTime($timestamp);
}
`
What could be the error

**Comment by EsoftsLimited** [comment]
Or how can i avoid yii query builder from placing quotes on ISOdate function? because the following query is running
`db.post.find({"created_at":{"$gte":ISODate("2017-01-31T23:59:59+0300"),"$lte":ISODate("2017-02-01T19:17:33+0300")},"type":"sms_outbox"})
`

**Comment by EsoftsLimited** [comment]
When i try to use Expression i get `
collectionName.command({"count":"animals","query":{"$and":[{"created_at":{"$gte":{"expression":"ISODate(\"2017-01-31T23:59:59+0300\")","params":[]},"$lte":{"expression":"ISODate(\"2017-02-01T19:27:20+0300\")","params":[]}}},{"type":"vaccinated"}]}})
`

**Comment by klimov-paul** [comment]
Can you successfully perform your quesy using plain PHP MongoDB driver?
Which PHP code is used fot it?

**Comment by EsoftsLimited** [comment]
I have played around with yii/mongodb/QueryBulder codes this almost gave me what i need
`
private function disenquote(&$value1,&$value2,&$x1IsBool=false,&$x2IsBool=false)
    {
       if ($value1 instanceof Expression) {
            $value1 = $value1->expression;
            $x1IsBool=true;
       }
       if ($value2 instanceof Expression) {
            $value2 = $value2->expression;
            $x2IsBool=true;
       }
       
    }

 public function buildBetweenCondition($operator, $operands)
    {
        if (!isset($operands[0], $operands[1], $operands[2])) {
            throw new InvalidParamException("Operator '$operator' requires three operands.");
        }
        list($column, $value1, $value2) = $operands;
      
        $this->disenquote($value1, $value2,$x,$y);
        if (strncmp('NOT', $operator, 3) === 0) {
            if($x || $y ){
                return [$column=>"{\$lt: $value1,\$gt: $value2 }"];
            }
            return [
                $column => [
                    '$lt' => $value1,
                    '$gt' => $value2,
                ]
            ];
        } else {
            if($x || $y ){
                return [$column=>"{\$lte: $value1,\$gte: $value2 }"];
            }
            return [
                $column => [
                    '$gte' => $value1,
                    '$lte' => $value2,
                ]
            ];
        }
    }
`
and the results
`
collectionName.command({"count":"animals","query":{"$and":[{"created_at":"{$lte: ISODate('2017-01-31T23:59:59+0300'),$gte: ISODate('2017-02-01T20:37:22+0300') }"},{"type":"vaccinated"}]}})
`

Notice the error at $and":[{" instead of $and":{" and it will run well

**Comment by EsoftsLimited** [comment]
Can you successfully perform your quesy using plain PHP MongoDB driver?
Which PHP code is used fot it?

Yes using php https://github.com/mongodb/mongo-php-library/tree/master/tests

**Comment by ElijahGM** [comment]
I was able to solve this by multiplying time-stamp by 1000 before conversion

**Comment by amitmmc1** [comment]
function to_date($datetime) {
        $timestamp = strtotime($datetime) * 1000;
        return new \MongoDB\BSON\UTCDateTime();
    }
$query->from("abc")
                            ->andFilterCompare('created_date',to_date($start), '$gte')
                            ->distinct('callingstationid');

unable to compare date condition
