### ISSUE TITLE
Compatibility with MongoDB 2.6

### ISSUE THREAD

**Issue by tehmaestro** [yiisoft/yii2-mongodb#184]
Hi, I just upgraded to 2.1.2 in an effort to prepare for an update on MongoDB server version, from 2.6 to 3.2 . I read that the mongodb driver supports server version 2.6,  but, as you mentioned in the upgrade guide, this extension does not support versions < 3.0
 Reading through the issues, I found this removal https://github.com/yiisoft/yii2-mongodb/issues/8

 Testing my code with version 2.1.2 and server 2.6, everything seemed ok. Is it ok to use this library with server version 2.6? As long as I avoid using the functionality that has been removed in the issue above?

Thank you so much.

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2-mongodb#installation

> This extension requires MongoDB server version 3.0 or higher.

**Comment by tehmaestro** [comment]
Hi, just a quick question if you could answer, is version 2.0.5, which uses the old driver, compatible with MongoDB Server greater than 3.0 ?
