### ISSUE TITLE
Unique Validator

### ISSUE THREAD

**Issue by ElijahGM** [yiisoft/yii2-mongodb#185]
### What steps will reproduce the problem?
I have thhis rule on model
`['title','unique','targetAttribute' => ['type','created_by'],`
i need each article written by the same author be unique,
### What's expected?
hence a user cannot write article of the same type
### What do you get instead?
The above rule is not executed thus it insert multiple articles at all but when i try 
`['title','unique','targetAttribute' => ['type','content']],`
It is executed by not inserting same articles i suspect its the field **created_by** which is of the type `\MongoDB\BSON\ObjectID`

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
Unable to reproduce. Following unit test runs successfully:

```php
public function testUniqueValidator()
    {
        $this->mockApplication();

        $user = new Customer();
        $user->name = 'test user';
        $user->save(false);

        $validator = new UniqueValidator([
            'targetAttribute' => ['type', 'created_by']
        ]);

        $item = new Item();
        $item->name = 'test';
        $item->type = 1;
        $item->created_by = $user->_id;
        $item->save(false);

        $item = new Item();
        $item->name = 'test';
        $item->type = 1;
        $item->created_by = $user->_id;

        $validator->validateAttribute($item, 'name');
        $this->assertTrue($item->hasErrors());

        $item->clearErrors();
        $item->type = 2;
        $validator->validateAttribute($item, 'name');
        $this->assertFalse($item->hasErrors());
    }
```

**Comment by ElijahGM** [comment]
Refer to my issue above,
 now i get this error 

`exception 'yii\base\ErrorException' with message 'Object of class module\user\models\User could not be converted to string' in /var/www/clients/client1/web7/vendor/yiisoft/yii2/validators/UniqueValidator.php:252 Stack trace: #0 /var/www/clients/client1/web7/vendor/yiisoft/yii2/base/ErrorHandler.php(177): yii\base\ErrorHandler->handleError() #1 /var/www/clients/client1/web7/vendor/yiisoft/yii2/validators/UniqueValidator.php(252): yii\base\ErrorHandler->handleHhvmError() #2 /var/www/clients/client1/web7/vendor/yiisoft/yii2/validators/UniqueValidator.php(137): yii\validators\UniqueValidator->addComboNotUniqueError() #3 `

Seems it has a new error now, when i add grouped unique validators any assistance i will appreciate
