### ISSUE TITLE
bug：php mongodb extension

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-mongodb#190]
bug:
in version 2.1.0 , require php mongo extension name is : ext-mongodb
```
 "require": {
        "yiisoft/yii2": "~2.0.5",
        "ext-mongodb": ">=1.0.0"
},
```

in version 1.~, php extension name is ext-mongo
```
"require": {
        "yiisoft/yii2": ">=2.0.5",
        "ext-mongo": ">=1.5.0"
    },
```
i think name `ext-mongodb` should change to  `ext-mongo`

when i install 2.x,it show errors:

```
 Problem 1
    - yiisoft/yii2-mongodb 2.1.3 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.2 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.1 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.0 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - fancyecommerce/fecshop 1.1.1 requires yiisoft/yii2-mongodb ~2.1.0 -> satisfiable by yiisoft/yii2-mongodb[2.1.0, 2.1.1, 2.1.2, 2.1.3].
    - Installation request for fancyecommerce/fecshop >=1.1.1 -> satisfiable by fancyecommerce/fecshop[1.1.1].

```

**Comment by fancyecommerce** [comment]
oh shit ,there is a php mongodb extension  
https://pecl.php.net/package/mongodb
and 
https://pecl.php.net/package/mongo

**Comment by shammi97** [comment]
G:\xampp\htdocs\hike18>composer require --prefer-dist yiisoft/yii2-mongodb
Using version ^2.1 for yiisoft/yii2-mongodb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-mongodb 2.1.7 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.6 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.5 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.4 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.3 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.2 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.1 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.0 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for yiisoft/yii2-mongodb ^2.1 -> satisfiable by yiisoft/yii2-mongodb[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
