### ISSUE TITLE
Gii: Getting unknown property: yii\mongodb\Connection::driverName

### ISSUE THREAD

**Issue by ElijahGM** [yiisoft/yii2-mongodb#191]
I am getting the above error while trying to generate crud using yii2 mongodb, my gii configuration
` $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'generators'=>[
           'class'=>'yii\mongodb\gii\model\Generator'
        ]
    ];`

On Class
`
 1. in /var/www/html/barcode/tooma/vendor/yiisoft/yii2/base/Component.php at line 147
138139140141142143144145146147148149150151152153154155156            if ($behavior->canGetProperty($name)) {
            return $behavior->$name;
        }
    }

    if (method_exists($this, 'set' . $name)) {
        throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
    }

    throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
}

/**
 * Sets the value of a component property.
 * This method will check in the following order and act accordingly:
 *
 *  - a property defined by a setter: set the property value
 *  - an event in the format of "on xyz": attach the handler to the event "xyz"
 *  - a behavior in the format of "as xyz": attach the behavior named as "xyz"
2. in /var/www/html/barcode/tooma/vendor/yiisoft/yii2-gii/generators/crud/Generator.php at line 564 – yii\base\Component::__get('driverName')
558559560561562563564565566     * @since 2.0.6
     */
    protected function getClassDbDriverName()
    {
        /* @var $class ActiveRecord */
        $class = $this->modelClass;
        return $class::getDb()->driverName;
    }
}

`

**Comment by klimov-paul** [comment]
Issue migrated to https://github.com/yiisoft/yii2-gii/issues/255
