### ISSUE TITLE
Add missing documentation about aggregation and other missing functions like group

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-mongodb#192]
There is no documentation for aggregation / pipelines and how it's working, also how to do groupBy and some other functions.

Can i open PR for this?

**Comment by cebe** [comment]
> Can i open PR for this?

of course you can, go ahead :)

**Comment by klimov-paul** [comment]
Resolved by commit e1b4e7348311a3cf79c19e4f9758ff8cd3c4a7d2
