### ISSUE TITLE
Why in the world it creates index for gridfs?

### ISSUE THREAD

**Issue by Lisio** [yiisoft/yii2-mongodb#195]
What was the reason to do this?
```
private function ensureFileIndexes()
{
    $indexKey = ['filename' => 1, 'uploadDate' => 1];
    foreach ($this->listIndexes() as $index) {
        if ($index['key'] === $indexKey) {
            return;
        }
    }

    $this->createIndex($indexKey);
}
```
This is the mongodb driver's job to create index to conform with GridFS specs and it's definetly never was the library's job. Now this useless method creates useless index on a huge fs.files collection in blocking mode with absolutely no reason to do so. This index will never be used for any purpose, but the project received an unexpected downtime for a long period. Great.

**Comment by klimov-paul** [comment]
> This is the mongodb driver's job to create index to conform with GridFS specs and it's definetly never was the library's job

It should be in this way - but it is not.
GridFS support is not handled by MongoDB server side, protocol or driver. Its support is a responsibility of the client.

**Comment by Lisio** [comment]
And I understand why it is not handled by the driver - it is not needed in some cases. For example, in our project, fs.files containes more than 20kk docs and all files are processed by their _id and metadata. We simply don't need this index, moreover it will waste cpu time, ram and disk, will slow down restore from backup and so on.
If you think that this index should be ensured - let us disable this feature via config. Just think about it - even creators of native mongodb driver do not create indexes on their own. Maybe they have a reason for that, don't they?

**Comment by klimov-paul** [comment]
> And I understand why it is not handled by the driver - it is not needed in some cases.

GridFS support is defined by mongodb.org docs, which says indexes should be created automatically.

If you wish custom processing you should operate GridFS collections directly or extend `yii\mongodb\file\Collection` class overridding `ensureIndexes()` method in your own way.

**Comment by Lisio** [comment]
> GridFS support is defined by mongodb.org docs, which says indexes should be created automatically.

By the driver, not by the third-party library.

> Drivers that conform to the GridFS specification will automatically ensure that this index exists before read and write operations.
https://docs.mongodb.com/manual/core/gridfs/

Library shouldn't emulate driver. And if driver will start ensuring indexes in the future - it will be overkill to ensure it twice.

**Comment by klimov-paul** [comment]
It seems you do not even listen.

GridFS is NOT suported by server-side, protocol or driver. Commands, which operate GridFS collections has NO difference from the ones used for regular collections.
GridFS is a high level convension defined by docs, which support **always** lies on the client software.

At old `mongo` PHP extension GridFS was built in specific classes, which were dropped at new `mongodb` driver.

**Comment by Lisio** [comment]
I know how GridFS works exactly. In [GridFS specs](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#indexes) it is noted that drivers must create indexes:

> Immediately before the first write operation on an instance of a GridFSBucket class is attempted (and not earlier), **drivers** MUST:
determine if the files collection is empty using the primary read preference mode.
and if so, create the indexes described above if they do not already exist

> **Drivers** MUST check whether the indexes already exist before attempting to create them.

> If a **driver** determines that it should create the indexes, it MUST raise an error if the attempt to create the indexes fails.

> **Drivers** MUST create the indexes in foreground mode.

Drivers, not any other kind of client software. But if you think that yii2-mongodb extension became a driver somehow than the word **driver** should be explicitly used in README.md similar to [mongodb driver description](https://pecl.php.net/package/mongodb). Right now it's behavior is unexpected and extension description causes misunderstanding on how it works.

**Comment by klimov-paul** [comment]
So you claim the `mongodb` driver creates GridFS indexes already and currect code is redundant?
Please provide the PHP code using plain `mongodb` PHP extension, which will prove your words then.

**Comment by Lisio** [comment]
I have never said that.
> And if driver will start ensuring indexes **in the future** - it will be overkill to ensure it twice.

I understand that new mongodb driver doesn't provide any layer for gridfs and it's support fully lays on yii2-mongodb so you decided to implement most of the missing features in respect to GridFS spec. I even understand that mongodb will always be some kind of low level driver by it's nature and will never support gridfs. The only thing I'm claiming about is that such driver-like behavior is not obvious and not expected from extension since this spec is written for drivers only which is said in it's header.

If you don't mind I'll create pull request to note this in readme and to add config option to disable it when necessary.

**Comment by klimov-paul** [comment]
Here you have quoted specs from mongodb.org https://github.com/yiisoft/yii2-mongodb/issues/195#issuecomment-287012390, which says:

> rivers MUST:
determine if the files collection is empty using the primary read preference mode.
and if so, create the indexes described above if they do not already exist

This is exactly what this extension do.

> I'm claiming about is that such driver-like behavior is not obvious and not expected from extension

Since this extension claims to provide support for MongoDB GridFS it **should** provide all features described at official specification, otherwise the support will be incomplete and it will be a bug.
