### ISSUE TITLE
Yii2-mongo DB distinct() returning only one column

### ISSUE THREAD

**Issue by ElijahGM** [yiisoft/yii2-mongodb#197]
### What steps will reproduce the problem?
when i try to get distinct rows with  column alias using the following command
` Collections::find()->where(['status'=>'queued'])->distinct('alias');`
### What's expected?
from a list of rows with the following

| Name          | alias        | Code
| ---------------- | ------------ | ------- 
| Nigrass       | attn          | 256615111
| Brass          | attn          | 125235529
| Grass          | attn          | 85555555
| Dress          | mvzi         | 85245445

i expect rows of all distinct rows with their attributes i.e 
`Array(
     array('name'=>"Nigrass",'alias'=>'attn','Code'=>'256615111'), // or any other row with attn alias
     array('name'=>"Dress",'alias'=>'mvzi','Code'=>'85245445'),
)`
### What do you get instead?
I get an array as follows with no attributes

`Array
(
    [0] => attn
)
`

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by klimov-paul** [comment]
This is expected behavior, method functions exactly as it is documented:
https://github.com/yiisoft/yii2-mongodb/blob/master/Query.php#L602
