### ISSUE TITLE
Yii2 Mongodb Command Exception : no such cmd: listCollections

### ISSUE THREAD

**Issue by afsolarte2** [yiisoft/yii2-mongodb#198]
### What steps will reproduce the problem?
1. Install Yii2 advanced template

2. Configure your mongodb Connnection (https://github.com/yiisoft/yii2-mongodb)

3. Configure MongoDb Model Generator (https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/topics-gii.md)

4. Open Gii url (localhost:8080/admin/gii)

5. Click on "MongoDB Model Generator -> Start"

### What's expected?

The "Gii Mongo Model generator" View

### What do you get instead?

An Exception page

MongoDB Exception – yii\mongodb\Exception
no such cmd: listCollections
Caused by: MongoDB\Driver\Exception\RuntimeException
no such cmd: listCollections
in /var/www/yii2-project/vendor/yiisoft/yii2-mongodb/Command.php at line 187

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.9
| Yii MongoDB version    |  2.1.3
| MongoDB server version | 2.4.10
| PHP version            | 5.6.30-0+deb8u1
| Operating system       | Linux - Debian 8 (Jessie)

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb#installation

> This extension requires MongoDB server version 3.0 or higher.
