### ISSUE TITLE
Implement createCommand (or similar)

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2-mongodb#20]
Having `createCommand` in `Connection` would be very useful as currently this extension is lacking some stuff that is possible to be done with a raw query.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/Database.php#L137

**Comment by alexandernst** [comment]
@klimov-paul I'm not really sure what should I pass to that method. What is a `* @param array $command command specification`? I tried looking in Google, but there doesn't seem to be anyone using that, and I couldn't find any further docs about this.

**Comment by alexandernst** [comment]
Oh, ignore that, I found out. That is actually the PHP MongoDB `command` method documented [here](http://php.net/manual/en/mongodb.command.php)

**Comment by alexandernst** [comment]
@klimov-paul Ok, so, from what I understand from the docs and from [this SO question](http://stackoverflow.com/questions/30150390/using-mongodbcommand-to-query), `MongoDB::command` is used to send raw  command to MongoDB, which is not quite the same as find, insert and other commands from [`MongoCollection::`](http://php.net/manual/en/class.mongocollection.php).

Going further in this issue, most of the commands from `MongoCollection::` are not exposed as [commands suitable for `MongoDB::command`](https://github.com/mongodb/mongo/tree/r3.0.2/src/mongo/db/commands), which means that yii's `executeCommand` is basically useless. 

IMHO Yii should provide a way to send actually query/update commands, which is what I was asking in the first place.
