### ISSUE TITLE
Yii::$app->session->getId() doesn't work in mongodb session component

### ISSUE THREAD

**Issue by amirkhh** [yiisoft/yii2-mongodb#202]
Yii::$app->session->getId() get empty string.

how can i get session id when im using mongodb session component (yii\mongodb\Session).

my config:

**'session' => [
            'class' => 'yii\mongodb\Session',
            'writeCallback' => function($session)
            {
                return [
                    'user_id' => Yii::$app->user->id,
                    'agent' => Yii::$app->request->getUserAgent(),
                    'ip' => Yii::$app->request->getUserIP(),
                ];
            }
        ],**

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |2
| Yii MongoDB version    |1.2.8
| MongoDB server version |3.4
| PHP version            |5.6
| Operating system       |Windows

**Comment by klimov-paul** [comment]
You need to manually start session before getting its ID:

```
Yii::$app->session->open();
return Yii::$app->session->id;
```
