### ISSUE TITLE
pageSize to less than 1 not infinite

### ISSUE THREAD

**Issue by ThePepster** [yiisoft/yii2-mongodb#203]
### What steps will reproduce the problem?
When setting the pageSize to less than 1 on Pagination for an ActiveDataProvider it means the page size should be infinite.  yii\mongodb\Command::find() has the effect of limiting the page size to 1 instead.

With this URL http://localdev/services/product-types?per-page=0 and the code below the results should be all documents in the collection but only the first document is returned.

    class ProductTypeController extends \yii\rest\ActiveController
    {
        public $modelClass = 'common\models\ProductType';

        public function actions()
       {
              $actions = parent::actions();

              // customize the data provider preparation with the "prepareDataProvider()" method
              $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];

              return $actions;
       }

       public function prepareDataProvider()
       {
               $modelClass = $this->modelClass;
               return \Yii::createObject([
                     'class' => \yii\data\ActiveDataProvider::className(),
                     'query' => $modelClass::find(),
                     'pagination' => [
                            'pageSizeLimit' => [0, 50],
                     ],
              ]);
       }
    }

### What's expected?
All documents in the collection.

### What do you get instead?
Only one document.

### Additional info
yii\mongodb\Command::find() line 603 should be changed from:

        if (array_key_exists('limit', $options)) {
            if ($options['limit'] === null) {
                unset($options['limit']);
            } else {
                $options['limit'] = (int)$options['limit'];
            }
        }

to:

        if (array_key_exists('limit', $options)) {
            if ($options['limit'] === null || $options['limit'] < 1) {
                unset($options['limit']);
            } else {
                $options['limit'] = (int)$options['limit'];
            }
        }

| Q                      | A
| ---------------------- | ---
| Yii version            |2.0.11.2
| Yii MongoDB version    |2.1.3
| MongoDB server version |3.4.3
| PHP version            |5.6.30
| Operating system       |Windows 10

**Comment by cebe** [comment]
I do not think it is a good idea to allow negative values for page size at all. you should disable pagination in that case. This should be adjuted in Pagination documentation.

**Comment by ThePepster** [comment]
I was just using MongoDB as the database for the backend of yii\rest\IndexAction.

It uses yii\data\ActiveDataProvider.

Which uses yii\data\Pagination.

yii\data\Pagination says:


    /**
    * Pagination represents information relevant to pagination of data items.
    ...
    * @property int $limit The limit of the data. This may be used to set the LIMIT value for a SQL statement for
    * fetching the current page of data. Note that if the page size is infinite, a value -1 will be returned. This
    * property is read-only.
    ...
    * @property int $pageSize The number of items per page. If it is less than 1, it means the page size is
    * infinite, and thus a single page contains all items.
    ...
    * @author Qiang Xue <qiang.xue@gmail.com>
    * @since 2.0
    */
    class Pagination extends Object implements Linkable
    ...

And:

    /**
     * @var int number of items on each page.
     * If it is less than 1, it means the page size is infinite, and thus a single page contains all items.
     */
    private $_pageSize;

And:

    /**
     * Returns the number of items per page.
     * By default, this method will try to determine the page size by [[pageSizeParam]] in [[params]].
     * If the page size cannot be determined this way, [[defaultPageSize]] will be returned.
     * @return int the number of items per page. If it is less than 1, it means the page size is infinite,
     * and thus a single page contains all items.
     * @see pageSizeLimit
     */
    public function getPageSize()
    {
    ...

And:

    /**
     * @return int the limit of the data. This may be used to set the
     * LIMIT value for a SQL statement for fetching the current page of data.
     * Note that if the page size is infinite, a value -1 will be returned.
     */
    public function getLimit()
    {

I just thought that if Pagination::$limit is going to be -1 that the MongoDB extension should know how to handle it and return all records instead of just one.  So I made yii\mongodb\Command::find() check if $options['limit'] is set and if it is but it is less than 1 then unset it because MongoDB won't understand that.

**Comment by klimov-paul** [comment]
Duplicates #205
