### ISSUE TITLE
Allow MongoDateVaildator mongoDateAttribute to be an array

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2-mongodb#206]
The case of this is having a rule like:

```php
            [
                ['current_index', 'first_index', 'last_index'],
                'yii\mongodb\MongoDateValidator',
                'format' => 'php:d/m/Y',
                'mongoDateAttribute' => 'current_index',
                'when' => function ($model) {
                    return $model->type === self::TYPE_DATE;
                },
                'whenClient' => "function (attribute, value) {
        			return $('#comic-type').val() == '" . self::TYPE_DATE . "';
    			}"
            ],
```

I want all of these to be casted to date objects but I would have to make three separate rules.

Would be better to be able to put an array of the attributes in the rule and for the validator to detect if the attribute it is on is in this array.

Hope that makes sense.

**Comment by klimov-paul** [comment]
Same as https://github.com/yiisoft/yii2/issues/10417

**Comment by Sammaye** [comment]
Though, mind you that is talking of trying to somehow map different attribute names. This would be far less complex since the validator is setting the attribute it is validating. It is just instead of having to write three rules separately I can write one

**Comment by cebe** [comment]
you can do something like this to not duplicate all the code:

```php
public function rules()
{
     $current = $first = $last = [
            '',
            'yii\mongodb\MongoDateValidator',
            'format' => 'php:d/m/Y',
            'mongoDateAttribute' => 'current_index',
            'when' => function ($model) {
                return $model->type === self::TYPE_DATE;
            },
            'whenClient' => "function (attribute, value) {
    		return $('#comic-type').val() == '" . self::TYPE_DATE . "';
            }"
     ];
     $current[0] = 'current_index';
     $first[0] = 'first_index';
     $last[0] = 'last_index';

    return [
         $current,
         $first,
         $last, 
// ...
     ];
}
```

**Comment by Sammaye** [comment]
Hehe yeah, that is actually what I did.

It just seemed like something that could be saved by adding a new bit of function
