### ISSUE TITLE
Make MongoDateValidator use `getTimestamp` on the `DateTime` object instead of `__toString`

### ISSUE THREAD

**Issue by Sammaye** [yiisoft/yii2-mongodb#207]
### What steps will reproduce the problem?

Have a field in the document that is already a UTCDateTime. Run the validator on this field.

### What's expected?

The date does not change

### What do you get instead?

The date changes to some crazy figure due to millisecond pollution from MongoDB.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.11.2
| Yii MongoDB version    | 2.1
| MongoDB server version | 3.x
| PHP version            | 7.1
| Operating system       | Ubuntu

**Comment by klimov-paul** [comment]
Resolved by commit a4d30dce8a54027186bed921c610277a0e8b5ee2
