### ISSUE TITLE
Add MongoIntValidator

### ISSUE THREAD

**Issue by ndobromirov** [yiisoft/yii2-mongodb#208]
### What steps will reproduce the problem?
Validation of an integer field to be stored in MongoDB. Pass in a string value that is a valid integer.
Have the field validation rules validate it as ```integer```.

### What's expected?
Possibility to use Int32 or int64 types to optimize storage space for the properties. Have the ability to Validate integer values and enforce storage format in MongoDB (similar to the MongoDateValidator).

### What do you get instead?
Once a string is passed to the input the default ```integer``` validator does nothing and a string is saved in DB. If we put requirements on integerOnly, then the client code is responsible for the casting, that would lead to code duplication, or needless implementations of ```beforeSave``` type casts, hindering maintainability of the code.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | latest 
| Yii MongoDB version    | 2.1.3
| MongoDB server version | 3.0.6
| PHP version            | 5.6
| Operating system       | Ubuntu 14.0

**Comment by klimov-paul** [comment]
Use [AttributeTypecastBehavior](https://github.com/yiisoft/yii2/blob/master/framework/behaviors/AttributeTypecastBehavior.php) to solve the issue.
