### ISSUE TITLE
Accessing MognoDB database

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2-mongodb#21]
Because of #19 and/or #20 I need to use PHP-MongoDB itself instead of Yii's functions, but I can't find a way to access the already defined database in my config. Example:

    $db = static::getDb()->mongoClient->selectDB("tests")->selectCollection("category");
    $db->find([...]);

That code works fine, but it seems unnecessary as I already told Yii in my config file that I'm using mongo and that my database is  `tests`. I'd expect to be able to get to a MongoDB instance with my database using something like:

    $db = Yii::$app->getDb(); // this returns the connection instead of a db. Method name is misleading

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/4711

**Comment by alexandernst** [comment]
@klimov-paul I think I'm asking for a different thing. My question is "Why can't I use the  already defined connection to my database?", while the issue you're linking to just clarifies that I can use `getCollection` to select both the database and the collection I want to query.

Plus, you completely ignored the comment I made about the misleading method name of  `getDb`.

**Comment by alexandernst** [comment]
@klimov-paul Same as the other issue. I'm feeling completely ignored and imho I'm asking valid questions.

**Comment by klimov-paul** [comment]
There is a <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> for question asking.
