### ISSUE TITLE
Can't connect to MongoDB cluster

### ISSUE THREAD

**Issue by SashaDesigN** [yiisoft/yii2-mongodb#217]
### What steps will reproduce the problem?
I try to configure yii2-mongodb on my project, installed it using composer, then add 

in config/web.php

```
'mongodb' => [
    'class' => '\yii\mongodb\Connection',
    'dsn' => 'mongodb://user:password@insta1-shard-00-00-s0vxe.mongodb.net:27017,insta1-shard-00-01-s0vxe.mongodb.net:27017,insta1-shard-00-02-s0vxe.mongodb.net:27017/database?ssl=true&replicaSet=Insta1-shard-0&authSource=admin',
]
```
and use this model:

```
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\mongodb\Query;

/**
 * BlogContent is the model behind the contact form.
 */
class BlogContent extends Model
{

    public function getPostList($page) {
        $query = new Query();
        // compose the query
        $rows = $query->select(['name', 'price', 'title'])
            ->from('services')->all();
    }

}
```

### What's expected?
it should return me all documents from the collection

### What do you get instead?
```
yii\base\UnknownMethodException: Calling unknown method: yii\mongodb\QueryBuilder::build() in /var/www/service/vendor/yiisoft/yii2/base/Object.php:220
Stack trace:
#0 /var/www/service/vendor/yiisoft/yii2/db/Query.php(126): yii\base\Object->__call('build', Array)
#1 /var/www/service/vendor/yiisoft/yii2/db/Query.php(213): yii\db\Query->createCommand(Object(yii\mongodb\Connection))
#2 /var/www/service/models/BlogContent.php(21): yii\db\Query->all()
#3 /var/www/service/controllers/BlogController.php(35): app\models\BlogContent->getPostList(1)
#4 [internal function]: app\controllers\BlogController->actionIndex(1)
#5 /var/www/service/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/service/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/service/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('index', Array)
#8 /var/www/service/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('blog/index', Array)
#9 /var/www/service/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /var/www/service/web/index.php(12): yii\base\Application->run()
#11 {main}
```

Then I try to use my local Mongo database instead of the cluster, it works fine. But it's not a problem with connection because I use the same cluster on my NodeJS App and connect to it from my the same laptop.

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | ~2.0.5
| Yii MongoDB version    | ~2.1.0
| MongoDB server version | MongoDB Atlas
| PHP version            | 7.0
| Operating system       | Ubuntu 16.04

**Comment by SashaDesigN** [comment]
It's not a question - it looks like you have a bug.

**Comment by klimov-paul** [comment]
> Stack trace: #0 /var/www/service/vendor/yiisoft/yii2/db/Query.php(126): yii\base\Object->__call('build', Array)

Once again `yii2/db/Query`. I can not see how connection DSN can make program code to pick the wrong class.
I have no time to debug your program - seek help at the forum.

**Comment by SashaDesigN** [comment]
Yes I understand, I fix this one by passing correct db connection to query:

```
$db = Yii::$app->mongodb;
$rows = $query->select(['name', 'price'])->from('services')->all($db);
```
and it start work with mongodb as you told above.
Then I test it on my local MongoDB database and it even connects and gets some data from collection, so I found what the problem is with the connection to MongoDB Atlas cluster.

**Comment by SashaDesigN** [comment]
I don't ask to help me debug my program, just told me how I can connect to MongoDB cluster.

**Comment by SashaDesigN** [comment]
I`m so sorry - the problem with on server (php7) side, I found what there was segmentation fault error and after I update php-mongodb its all start to work. Also if someone will have segmentation fault error it may be a problem with your PHP configuration.

Thanks for support, catch your star:)
