### ISSUE TITLE
gii get no such cmd: listCollections

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2-mongodb#218]
### What steps will reproduce the problem?
use debug  module generat  mongodb models

### What's expected?
can use

### What do you get instead?
no such cmd: listCollections

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |2.0.12
| Yii MongoDB version    |2.1.4.0
| MongoDB server version |1.2.9 
| PHP version            |5.6.30
| Operating system       |centos

**Comment by klimov-paul** [comment]
Duplicates #188
