### ISSUE TITLE
yii\base\ViewNotFoundException: The view file does not exist

### ISSUE THREAD

**Issue by miholeus** [yiisoft/yii2-mongodb#221]
### What steps will reproduce the problem?
`php yii mongodb-migrate/create test`
### What's expected?
New file for migration
### What do you get instead?
https://github.com/yiisoft/yii2-mongodb/issues/96#issuecomment-319710520

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.12
| Yii MongoDB version    | 2.1.4
| MongoDB server version |
| PHP version            | 7
| Operating system       |

**Comment by miholeus** [comment]
Filepaths are not correct.
```
Exception 'yii\base\ViewNotFoundException' with message 'The view file does not exist: /app/vendor/yiisoft/yii2/mongodb/views/migration.php'
```
But the file is located here
`/app/vendor/yiisoft/yii2-mongodb/views/migration.php`

**Comment by miholeus** [comment]
Default path is set here
`https://github.com/yiisoft/yii2-mongodb/blob/master/console/controllers/MigrateController.php#L83
`
Maybe it should be changed?

**Comment by klimov-paul** [comment]
Unable to reproduce.
Make sure you have installed `yii2-mongodb` properly via composer.

**Comment by miholeus** [comment]
I did, but in my case I do not have `@yii/mongodb` in `BaseYii::aliases`, that's why it does not work.
I've checked it on clean installation, it works there, because that alias is present in array.

**Comment by cebe** [comment]
If it works on a clean installation there is something broken in your instance, nothing that can be fixed from our side.
