### ISSUE TITLE
orderBy and distinct does not give sorted result

### ISSUE THREAD

**Issue by harrytang** [yiisoft/yii2-mongodb#226]
username | group | email
-- | -- | --
abc | member | abc@xyz.com
abc1 | admin | abc1@xyz.com
abc2 | vip | abc2@xyz.com
abc3 | member | abc3@xyz.com

### What steps will reproduce the problem?
(new yii\mongodb\Query)->select(['group'])->from('users')->orderBy('group')->distinct('group');

### What's expected?
admin
member
vip

### What do you get instead?
member
admin
vip

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.12
| Yii MongoDB version    |2.1.4
| MongoDB server version |3.4.7
| PHP version            |7.1.7
| Operating system       |Windows 10.0 build 15063

**Comment by klimov-paul** [comment]
This is expected behavior as MongoBD `distinct` does not support sorting:
https://docs.mongodb.com/manual/reference/method/db.collection.distinct/
