### ISSUE TITLE
mongo extension error

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii2-mongodb#230]
### What steps will reproduce the problem?
`MongoClient` not found on php7.0 version
### What's expected?
fix
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.13-dev
| Yii MongoDB version    | 2.0.5
| MongoDB server version | v3.4.7
| PHP version            | 7.0
| Operating system       | Linux Debian 8.0 Jessie

**Comment by samdark** [comment]
http://php.net/manual/en/class.mongoclient.php

**Comment by cebe** [comment]
> MongoClient not found on php7.0 version

did you install it?

**Comment by rustamwin** [comment]
yes i set it all

**Comment by rustamwin** [comment]
yes i set it all

**Comment by rustamwin** [comment]
Did anyone use it?

**Comment by klimov-paul** [comment]
Duplicates #48
