### ISSUE TITLE
Update extension yii2-mongodb

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii2-mongodb#235]
### What steps will reproduce the problem?
update version with composer
### What's expected?
the requested PHP extension mongodb is missing from your system
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.13
| Yii MongoDB version    | 2.0.5
| MongoDB server version | 3.2.7
| PHP version            | 5.6
| Operating system       | linux

**Comment by samdark** [comment]
> the requested PHP extension mongodb is missing from your system

**Comment by rustamwin** [comment]
my php extension : 
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-gd.ini,
/etc/php5/cli/conf.d/20-gmp.ini,
/etc/php5/cli/conf.d/20-imagick.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mcrypt.ini,
/etc/php5/cli/conf.d/20-mongo.ini,
/etc/php5/cli/conf.d/20-mysql.ini,
/etc/php5/cli/conf.d/20-mysqli.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-pdo_sqlite.ini,
/etc/php5/cli/conf.d/20-readline.ini,
/etc/php5/cli/conf.d/20-sqlite3.ini,
/etc/php5/cli/conf.d/20-xsl.ini
