### ISSUE TITLE
yii\mongodb\Query max/min/sum problem

### ISSUE THREAD

**Issue by harrytang** [yiisoft/yii2-mongodb#241]
### What steps will reproduce the problem?
use yii\mongodb\Query;

$maxPoint = (new Query())
    ->from('users')
    ->where(['status' => 'STATUS_ACTIVE'])
    ->max('point');

### What's expected?
The number of point, example: 10000

### What do you get instead?
MongoDB\Driver\Exception\RuntimeException: The 'cursor' option is
required, except for aggregate with the explain argument in ...

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.13.1
| Yii MongoDB version    | 2.1.5
| MongoDB server version | 3.6
| PHP version            | 7.1
| Operating system       | Ubuntu 16 LTS

**Comment by klimov-paul** [comment]
Resolved by commit 0ad02a4750474ffaf43262c7203cf83836fe88e1
