### ISSUE TITLE
Possible to add allowDiskUse to aggregate function

### ISSUE THREAD

**Issue by alexjeen** [yiisoft/yii2-mongodb#245]
Aggregate function has a allowDiskUse: true parameter, how can I pass this into this library?

https://docs.mongodb.com/manual/reference/command/aggregate/

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/Command.php#L726

**Comment by amirajlo** [comment]
@klimov-paul
https://github.com/yiisoft/yii2-mongodb/blob/master/Command.php#L726
the page not found

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/blob/master/src/Command.php#L726
