### ISSUE TITLE
mongodb extension can release a new version? To facilitate us to install the latest version of the code to deal with the bug

### ISSUE THREAD

**Issue by fancyecommerce** [yiisoft/yii2-mongodb#246]
mongodb extension can release a new version?
To facilitate us to install the latest version of the code to deal with the bug

**Comment by klimov-paul** [comment]
There will be no release before yii2 2.0.14 version.
Future version 2.1.6 of 'yii2-mongodb' is likely to be the last at 2.1.x.

**Comment by fancyecommerce** [comment]
@klimov-paul  About when to release Yii2 version 2.0.14. ？  thank you

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/milestones
