### ISSUE TITLE
query with relation not work  

### ISSUE THREAD

**Issue by lotos2512** [yiisoft/yii2-mongodb#250]
### What steps will reproduce the problem?
This query with relation must be give me result but is  not working

```php
$query->where(['title' => ['$regex' => $this->getSearchQuery()]]);
$query->orWhere(['type' => ['$in' => [
TickerFactory::TYPE_SHARE,
TickerFactory::TYPE_OBLIGATION,
]]])->with(['companyModel' => function ($companyQuery) {
$companyQuery->andWhere(['title' => ['$regex' => $this->getSearchQuery()]]);
}]);
```

### What's expected?
This query relation must be give me result of relation companyModel but is  not working. When i do --- 

```php
$query->where(['title' => ['$regex' => $this->getSearchQuery()]]);
$query->orWhere(['type' => ['$in' => [
TickerFactory::TYPE_SHARE,
TickerFactory::TYPE_OBLIGATION,
]]])->with(['companyModel']);
}]);
```
It is worked 

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.13
| Yii MongoDB version    | 2.6 
| MongoDB server version |   XXX
| PHP version            | 7.2 
| Operating system       | ubunty

**Comment by samdark** [comment]
How exactly it doesn't work? Throwing an exception?

**Comment by lotos2512** [comment]
i maked  two the  models (Ticker - Company) and relations for them. Relation is worked but without $query->with(['companyModel' => function ($companyQuery) {
$companyQuery->andWhere(['title' => ['$regex' => $this->getSearchQuery()]]);
}]).(the variable $query is  ActiveQuery of model Ticker )Throwing an exception not have. In result i get null in the relation companyModel

**Comment by samdark** [comment]
That means that condition you've specified results in now record found.

**Comment by lotos2512** [comment]
but when i do
```php
Company::find()->where(['title' => ['$regex' => $this->getSearchQuery()]]);
```
i get not empty result
