### ISSUE TITLE
ActiveDataProvider and relationships

### ISSUE THREAD

**Issue by KryDos** [yiisoft/yii2-mongodb#26]
Hello,
I found that *Where conditions don't work with relationships. Let me provide example:

here is part of my search() method:
```php
        $query = Post::find()->with('author');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        $query->andWhere(['author.first_name'=>'TestName']) // this do not work
```
Model is trying to find **author.first_name** field in the **post** collection. I think it should search for **first_name** in **author** collection.

I hope I didn't lost something... Maybe I'm using it in wrong way or conditions using relations are not implemented in mongodb driver?

Hoping on your help. 

Thank you.

**Comment by klimov-paul** [comment]
This is not implementable since MongoDB does not allows collection joins.

**Comment by KryDos** [comment]
Thank you for your answer.
