### ISSUE TITLE
When install mongo in yii2 advanced

### ISSUE THREAD

**Issue by shammi97** [yiisoft/yii2-mongodb#280]
G:\xampp\htdocs\hike18>composer require --prefer-dist yiisoft/yii2-mongodb
Using version ^2.1 for yiisoft/yii2-mongodb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-mongodb 2.1.7 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.6 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.5 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.4 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.3 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.2 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.1 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - yiisoft/yii2-mongodb 2.1.0 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for yiisoft/yii2-mongodb ^2.1 -> satisfiable by yiisoft/yii2-mongodb[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by shammi97** [comment]
Please help me ASAP. It's urgent.

**Comment by samdark** [comment]
You should have mongodb PECL extension installed and enabled in your php.ini.

**Comment by shammi97** [comment]
I already install and also enable

**Comment by shammi97** [comment]
![image](https://user-images.githubusercontent.com/52040142/60716586-710cda80-9f3d-11e9-8197-831b10978818.png)

**Comment by shammi97** [comment]
![image](https://user-images.githubusercontent.com/52040142/60716611-8124ba00-9f3d-11e9-9574-5c19fcfdcc66.png)

**Comment by samdark** [comment]
Well, the error says it isn't. Likely php.ini isn't used from console.

**Comment by shammi97** [comment]
can you tell what is the folder structure

**Comment by shammi97** [comment]
Actually mongo is working in my local simple php program but when i install mongo in yii2 advanced project using 

composer require --prefer-dist yiisoft/yii2-mongodb

then give error
