### ISSUE TITLE
Issue in Installation of yii2 and mongodb

### ISSUE THREAD

**Issue by shammi97** [yiisoft/yii2-mongodb#281]
Hello All,

I have yii2 advanced
mongo ext version 1.6.8
php version 5.6

I'm not abel to install mongo extension in yii2 ? what is an issue?

Thanks
Shammi

**Comment by shammi97** [comment]
This error came in yesterday

yiisoft/yii2-mongodb 2.1.7 requires ext-mongodb >=1.0.0 -> the requested PHP extension mongodb is missing from your system.

**Comment by samdark** [comment]
What's the output of `php -i | grep mongodb`?

**Comment by shammi97** [comment]
mongodb
mongodb.debug => no value => no value
Path => C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\nodejs\;C:\xampp\php;G:\xampp;C:\Users\ITSS1\AppData\Local\Microsoft\WindowsApps;C:\Users\ITSS1\AppData\Roaming\npm;C:\Users\ITSS1\AppData\Roaming\Composer\vendor\bin;C:\xampp\php;";G:\xampp\php";G:\mongodb\bin;
$_SERVER['Path'] => C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\nodejs\;C:\xampp\php;G:\xampp;C:\Users\ITSS1\AppData\Local\Microsoft\WindowsApps;C:\Users\ITSS1\AppData\Roaming\npm;C:\Users\ITSS1\AppData\Roaming\Composer\vendor\bin;C:\xampp\php;";G:\xampp\php";G:\mongodb\bin;

**Comment by samdark** [comment]
You should install mongodb extension, not mongo. The later is legacy one.
