### ISSUE TITLE
Error in Swift_TransportException 

### ISSUE THREAD

**Issue by shammi97** [yiisoft/yii2-mongodb#282]
Actually this is working on server but not work on my localhost 

![image](https://user-images.githubusercontent.com/52040142/61287460-8fe35a80-a7e2-11e9-93cf-30a2f379a08d.png)

**Comment by samdark** [comment]
How's that connected with mongodb?

**Comment by shammi97** [comment]
in mongodb version issue with php mongoextension and yii.

**Comment by shammi97** [comment]
can you tell me about this problem

**Comment by samdark** [comment]
That's swiftmailer exception that is not connected to mongodb in any way.
