### ISSUE TITLE
MongoDB DropIndexes() fails when there is no index

### ISSUE THREAD

**Issue by xiaoyi510** [yiisoft/yii2-mongodb#286]
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2
| Yii MongoDB version    | 2.1.7
| MongoDB server version |4.x
| PHP version            | 7.2
| Operating system       | LINUX

MongoDB DropIndexes() fails when there is no index

```php
\yii\mongodb\Collection::dropAllIndexes
/**
     * Drops all indexes for this collection.
     * @throws Exception on failure.
     * @return int count of dropped indexes.
     */
    public function dropAllIndexes()
    {
        $result = $this->database->createCommand()->dropIndexes($this->name, '*');
        return $result['nIndexesWas'];
    }
```

nIndexesWas index does not return this field when deleting a collection without an index

Should be

```php
  public function dropAllIndexes()
    {
        $result = $this->database->createCommand()->dropIndexes($this->name, '*');
        return $result['nIndexesWas']??0;
    }
```

**Comment by samdark** [comment]
Looks valid. Do you want to prepare a pull request?
