### ISSUE TITLE
Why we not implement db transaction to mongodb?

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2-mongodb#29]

**Comment by cebe** [comment]
because mongodb does not support transactions.

**Comment by TheHett** [comment]
@cebe transaction is possible on the client side,
when we started to write Yii2, it had the similar abilty

**Comment by cebe** [comment]
can you point to some docs about that? I could not find any...

**Comment by TheHett** [comment]
here https://github.com/yiisoft/yii2/issues/11

**Comment by cebe** [comment]
I do not see anything about transactions in the linked docs...

**Comment by TheHett** [comment]
hmm, maybe I misunderstood

![image](https://cloud.githubusercontent.com/assets/946246/9136542/4c33666c-3d39-11e5-9c90-3aae0daaf4d0.png)

**Comment by cebe** [comment]
The list is copy from SQL layer, the question mark indicates that there was no information on whether such feature is provided by mongo or not. And as far as I know there is no such feature in mongodb. If you find it, point us to the docs and we can try implement it.

**Comment by TheHett** [comment]
Hm, maybe only Two Phase Commits
http://docs.mongodb.org/manual/tutorial/perform-two-phase-commits/
but it not easy, i think

**Comment by sebathi** [comment]
https://techcrunch.com/2018/02/15/mongodb-gets-support-for-multi-document-acid-transactions/

**Comment by sebathi** [comment]
It is totally suported now. 

We should be able to use them ;)

https://www.mongodb.com/transactions

**Comment by effsoft** [comment]
It's very important update.

**Comment by devkdouglass** [comment]
Adding some examples in case anyone else runs into issues. I got hung while trying to add the session to the `$options` parameter in  the `yii\mongodb\Collection` methods. 

**With Yi2 Mongodb Extension**
```
$client = Yii::$app->mongodb;
$session = $client->manager->startSession();
$session->startTransaction();

try {
    $client->createCommand()
           ->addInsert(['key' => 'value'])
           ->setWriteConcern(['session' => $session])
           ->executeBatch('COLLECTION');

    // Uncomment to prevent transaction
    // throw new \Exception('Force fail. Stop transaction.');

    $session->commitTransaction();

} catch (\Exception $error) {
    $session->abortTransaction();
    print_r($error->getMessage());
} 
```

**Without Yii2 Mongodb Exension**
```
$client = Yii::$app->mongodb->manager;
$session = $client->startSession();
$session->startTransaction();

try {
    $bulk = new \MongoDB\Driver\BulkWrite;
    $bulk->insert(['key' => 'value']);
    $client->executeBulkWrite('DB.COLLECTION', $bulk, ['session' => $session]);

    // Uncomment to prevent transaction
    /// throw new \Exception('Force fail. Stop transaction.');

    $session->commitTransaction();

} catch (\Exception $error) {
    $session->abortTransaction();
     print_r($error->getMessage());
}
```

**Comment by maharjanmilan** [comment]
> $client = Yii::$app->mongodb;
> $session = $client->manager->startSession();

Manger is null here. Whats the issue?

**Comment by devkdouglass** [comment]
If I remember correctly and depending on your environment, you may need to install `ext-mongodb` to add the core API functionality, along with the MongoDB Driver. Make sure the `mongodb.so` extension exists in your PHP.ini file. 

Also, I believe transactions are only available with Replicas(at least with Mongo Atlas) and MongoDB 4.2.
