### ISSUE TITLE
Incorrect exception in User::loginRequired?

### ISSUE THREAD

**Issue by Lisio** [yiisoft/yii2-mongodb#295]
Why User::loginRequired throws ForbiddenHttpException and not UnauthorizedHttpException?

**Comment by samdark** [comment]
Is it somehow connected to mongodb?

That's done only if redirection can't be done. Thus, user won't be asked to authorize.

**Comment by Lisio** [comment]
Sorry, I mixed up the repos. The issue is related to core yii2.
Anyway, if user is not authenticated we should throw 401 regardless of redirect, not 403.
```
401 Unauthorized actually means the user is not authenticated while 403 Forbidden means the user is not authorized to perform the action they are trying to do.
```

**Comment by samdark** [comment]
I do not agree. 401 is thrown if there's a chance given to enter credentials. In case there's no redirect to login form, there's no chance and a fact that access is forbidden.

**Comment by Lisio** [comment]
This is arguable enough since there is a chance to send credentials using headers, i.e. authorization token with AJAX requests.
This is mostly related to the cases when we use both AJAX and AccessControl filter in behaviors. In such situation we always receive 403 even if authorization is possible.

**Comment by samdark** [comment]
Hmm, yes, that use-case looks possible. Can you create a new issue in yiisoft/yii2 describing the use case in more detail? Thanks.
