### ISSUE TITLE
How to get relation A to C through B?

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2-mongodb#30]
In yii\db\ActiveQuery we can usage:
```php
 /**
     * @return \yii\db\ActiveQuery
     */
    public function getC()
    {
        return $this->hasMany(C::className(), ['c_id' => 'bc_id'])->viaTable(B::tableName(), ['ab_id' => 'a_id']);
    }
```
but on yii\mongodb\ActiveRecord not supported method tableName and viaTable on yii\mongodb\ActiveQuery . i want use `one method` and don't want using `two method` as

```php
class A extends ActiveRecord
{
    public function getBC()
    {
        return $this->hasMany(B::className(), ['ab_id' => 'id']);
    }

    public function getC()
    {
        return $this->hasMany(C::className(), ['id' => 'bc_id'])
            ->via('bC');
    }
}
```
other way ?

**Comment by cebe** [comment]
as mongodb storage does not support junction tables you have to use two methods. There is no other way.

**Comment by zinzinday** [comment]
Yes, mongodb not support junction tables but why we not implement method viaCollection is replacement for viaTable in RDBMS SQL

**Comment by klimov-paul** [comment]
Usually it does not make any sense: you can use array (set) value to collect all references to the other collection, so there is no need in juction collection at all:
```
{
    _id: ...,
    realated_ids: [2, 5, 8, 11],
}
```

**Comment by zinzinday** [comment]
It not good bcos yii2 not support Embedded Documents. that will be more difficult to validate form
