### ISSUE TITLE
File Upload opens file in write mode

### ISSUE THREAD

**Issue by sparchatus** [yiisoft/yii2-mongodb#308]
When uploading a file it is opened read/write. This causes a permission error when the web server has read only access to the file.

https://github.com/yiisoft/yii2-mongodb/blob/837c14c8a38055cd97d6f8b551eef27616f3c8c5/src/file/Upload.php#L175-L186

**Comment by samdark** [comment]
Looks like a bug. I see no reason to open it for reading in this case.
