### ISSUE TITLE
->one() dosent work , need to add limit(1)

### ISSUE THREAD

**Issue by jarooghe** [yiisoft/yii2-mongodb#309]
### What steps will reproduce the problem?
i had a collection with 150000 document , server was  run very slowly ... after check , i got that query for database cause slow , after add ->limit(1) , problem solved 
### What's expected?
i expected to by using ->one() its add limit(1) to query 
### What do you get instead?
adding ->limit(1)

### Additional info
this is my last query

        $next = News::find()->where([
            '>','id',$model->id
        ])
            ->andWhere(['main_service'=>$model->main_service])
            ->orderBy('id')
            ->limit(1) // added after finding problem 
            ->one();

| Q                      | A
| ---------------------- | ---
| Yii version            | ~2.0.14 
| Yii MongoDB version    | ^2.1 
| MongoDB server version |  4.2
| PHP version            | 7.4
| Operating system       | Windows server 2018

**Comment by samdark** [comment]
Is it similar to https://github.com/yiisoft/yii2-mongodb/issues/303?

**Comment by jarooghe** [comment]
yes , it is simillar, adding limit 1 to ->one() fix both query time and memory

**Comment by jarooghe** [comment]
so i close this ...
