### ISSUE TITLE
using trim filter on a non-required field insert an empty ercord to mongoDB

### ISSUE THREAD

**Issue by alirezastack** [yiisoft/yii2-mongodb#32]
In a mongoDB ActiveRecord when I use the below rule on a specific field, an empty field will be added to my collection:

`[['parent', 'children'],'filter','filter'=>'trim'],`

Is this is a bug? do we have workaround for it?

**Comment by klimov-paul** [comment]
@alirezastack, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
