### ISSUE TITLE
PECL 1.9.0 crashes BatchQueryResult

### ISSUE THREAD

**Issue by alexjeen** [yiisoft/yii2-mongodb#327]
### What steps will reproduce the problem?

Just read via an iterator via each() on MongoDB PECL version 1.9.0 (released a couple of days ago) they changed something in the Cursor: * [PHPC-1691] - Iterator implementation for MongoDB\Driver\Cursor

### What's expected?

The data returns without crashing.

### What do you get instead?

    PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: row'

    in /var/app/vendor/yiisoft/yii2-mongodb/src/BatchQueryResult.php:150

    Stack trace:
    #0 /var/app/vendor/yiisoft/yii2-mongodb/src/BatchQueryResult.php(150): yii\base\ErrorHandler->handleError(8,     'Undefined varia...', '/var/app/vendor...', 150, Array)
    #1 /var/app/vendor/yiisoft/yii2-mongodb/src/BatchQueryResult.php(101): yii\mongodb\BatchQueryResult->fetchData()
    #2 /var/app/vendor/yiisoft/yii2-mongodb/src/BatchQueryResult.php(91): yii\mongodb\BatchQueryResult->next()

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.39
| Yii MongoDB version     | 2.1.10
| MongoDB server version PECL  | 1.9.0
| PHP version            | PHP 7.2.16 (cli)
| Operating system       | Alpine

**Comment by alexjeen** [comment]
If you encounter this issue just downgrade to 1.8.2 to get your setup to play nicely. I can confirm this works:

    # install mongodb
    RUN pecl install mongodb-1.8.2 && docker-php-ext-enable mongodb

**Comment by bizley** [comment]
I wonder if changing

```php
while ($count++ < $this->batchSize) {
    $row = $this->_iterator->current();
    if ($row === null) {
        break;
    }
    $this->_iterator->next();
    $rows[] = $row;
}
```

with

```php
while ($count++ < $this->batchSize) {
    if (!$this->_iterator->valid()) {
        break;
    }
    $rows[] = $this->_iterator->current();
    $this->_iterator->next();
}
```

would help...

**Comment by ziaratban** [comment]
@samdark
this is not a bug in yii2. this is a bug in php mongodb driver.
https://github.com/mongodb/mongo-php-driver/issues/1183

@alexjeen
So you can fix this error right now.
https://github.com/ziaratban/yii2-mongodb/commit/a1f2945483d2a134a5ad3a383dae663e5dd171a0

**Comment by bizley** [comment]
Yes, but corrected implementation works well with both this and the older driver so we don't have to wait for `mongodb` maintainers.
