### ISSUE TITLE
Class 'MongoDB\Driver\BulkWrite' not found

### ISSUE THREAD

**Issue by juneldmm** [yiisoft/yii2-mongodb#329]
### What steps will reproduce the problem?
use yii\mongodb\ActiveRecord;
//类名 对应到数据表名称
class mongoTest extends ActiveRecord
{
    public static function add($controllerId, $actionId, $getParams, $postParams, $userId, $userName, $league_id, $league_name, $remoteAddr, $httpUserAgent, $createDatetime)
    {
        $log = new mongoTest();
        $log->_id = time();
        $log->controllerId = $controllerId;
        $log->actionId = $actionId;
        $log->getParams = $getParams;
        $log->postParams = $postParams;
        $log->userId = $userId;
        $log->userName = $userName;
        $log->league_id = $league_id;
        $log->league_name = $league_name;
        $log->remoteAddr = $remoteAddr;
        $log->httpUserAgent = $httpUserAgent;
        $log->createDatetime = $createDatetime;
        $log->durationTime = null;
        $log->exceptionCode = null;
        $log->exceptionMessage = null;
        $log->exceptionTraceMessage = null;
        $result = $log->save();
        if ($result == true) {
            return $log->_id;
        } else {
            return null;
        }
    }
}
### What do you get instead?
Class 'MongoDB\Driver\BulkWrite' not found

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0
| Yii MongoDB version    | 2.1.9
| MongoDB server version |4.4.1
| PHP version            |7.1.23
| Operating system       |  macOS 10.14.6

**Comment by bizley** [comment]
Is it something like described in here? https://stackoverflow.com/questions/38766586/fatal-error-class-mongodb-driver-manager-not-found
