### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: mongodb'

### ISSUE THREAD

**Issue by nagarjuna-iccs** [yiisoft/yii2-mongodb#334]
Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: mongodb'

in /var/www/html/1t_crm/vendor/yiisoft/yii2/di/ServiceLocator.php:139

Stack trace:
#0 /var/www/html/1t_crm/vendor/yiisoft/yii2/base/Module.php(748): yii\di\ServiceLocator->get()
#1 /var/www/html/1t_crm/vendor/yiisoft/yii2-mongodb/src/Query.php(72): yii\base\Module->get()
#2 /var/www/html/1t_crm/vendor/yiisoft/yii2-mongodb/src/Query.php(199): yii\mongodb\Query->getCollection()
#3 /var/www/html/1t_crm/vendor/yiisoft/yii2-mongodb/src/Query.php(325): yii\mongodb\Query->buildCursor()
#4 /var/www/html/1t_crm/commands/CarrierController.php(38): yii\mongodb\Query->all()
#5 /var/www/html/1t_crm/commands/CarrierController.php(32): app\commands\CarrierController->activeinactive()
#6 [internal function]: app\commands\CarrierController->actionIndex()
#7 /var/www/html/1t_crm/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /var/www/html/1t_crm/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#9 /var/www/html/1t_crm/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#10 /var/www/html/1t_crm/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#11 /var/www/html/1t_crm/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#12 /var/www/html/1t_crm/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#13 /var/www/html/1t_crm/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#14 /var/www/html/1t_crm/yii(20): yii\base\Application->run()
#15 {main}

**Comment by nagarjuna-iccs** [comment]
configuration in console.php...solved my problem

**Comment by irmapiana** [comment]
can you please share how to solved the problem with configuring console.php? because i face the same problem
