### ISSUE TITLE
ActiveRecord object return with values null

### ISSUE THREAD

**Issue by Kutuzovska** [yiisoft/yii2-mongodb#336]
### What steps will reproduce the problem?
I am using **"yiisoft/yii2-mongodb": "^2.1"**
but have problem with ActiveRecord.
![image](https://user-images.githubusercontent.com/34393267/121053525-213b8b80-c7c4-11eb-9320-809d838dad5d.png)
![image](https://user-images.githubusercontent.com/34393267/121053580-2ac4f380-c7c4-11eb-873f-d8e0a3851488.png)

### What's expected?
![image](https://user-images.githubusercontent.com/34393267/121053743-5647de00-c7c4-11eb-8ac0-549afaa03261.png)
![image](https://user-images.githubusercontent.com/34393267/121053773-5e078280-c7c4-11eb-8616-5bb9d2a92863.png)

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2
| Yii MongoDB version    | 2.1
| MongoDB server version |
| PHP version            | 8
| Operating system       | docker

**Comment by bizley** [comment]
What is in `$username`? Are you sure that data is in the DB? Are other rows fetched properly?

**Comment by Kutuzovska** [comment]
> What is in `$username`? Are you sure that data is in the DB? Are other rows fetched properly?

$username is post param, is Ok.  with asArray query is work and other collections. But object with values null

**Comment by bizley** [comment]
Have you followed steps mentioned here? https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/usage-ar.md

**Comment by Kutuzovska** [comment]
> Have you followed steps mentioned here? https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/usage-ar.md

Yep. have collect names, have attributtes. May be error in _id.$oid 
![image](https://user-images.githubusercontent.com/34393267/121121327-0dc20c00-c828-11eb-9eb5-1bba5279423d.png)

**Comment by Kutuzovska** [comment]
Sorry... I'am understand, but other field have value
![image](https://user-images.githubusercontent.com/34393267/121131935-2981de00-c839-11eb-91ae-5c77efb75178.png)

**Comment by Kutuzovska** [comment]
![image](https://user-images.githubusercontent.com/34393267/121133282-d27d0880-c83a-11eb-807d-4c39f3af94fb.png)
Sorry, it's my mistake
