### ISSUE TITLE
update docs folder link

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii2-mongodb#362]
### What steps will reproduce the problem?
http=>https
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            |
| Yii MongoDB version    |
| MongoDB server version |
| PHP version            |
| Operating system       |

**Comment by mtangoo** [comment]
Can you point the link you are referring to, or even better make a PR?

**Comment by mtangoo** [comment]
closing for https://github.com/yiisoft/yii2-mongodb/issues/360
