### ISSUE TITLE
Will you support the 'driver_options' in Connection.php

### ISSUE THREAD

**Issue by vistart** [yiisoft/yii2-mongodb#41]
Now the Connection doesn't include the 'driver_options' property, and the MongoClient::__construct() method which is in the open() method doesn't transfer the third parameter 'driver_options'.
Will you support the 'driver_options' in Connection.php? If it were supported, we will use SSL in convinient way.

**Comment by klimov-paul** [comment]
Resolved by commit a14cdd51658c55164e613fdd19fb4c20530df36a

**Comment by vistart** [comment]
Resolved by commit cc12645
