### ISSUE TITLE
MongoDB Migrate - Invalid data type: yii\mongodb\Connection. yii\db\Connection is expected

### ISSUE THREAD

**Issue by fakixlix** [yiisoft/yii2-mongodb#42]
![2015-08-24-021656_1366x768_scrot](https://cloud.githubusercontent.com/assets/4468829/9433262/5773d186-4a06-11e5-9710-7d19a9d3f621.png)

Hi everybody. I try to migrate to mongodb with a collection named users but in the console is shows this error. Help me :O

**Comment by cebe** [comment]
for mongodb migrations you have to configure application to use the correct migration controller: https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/topics-migrations.md
for further questions, please use the forum.

**Comment by twegs0ed** [comment]
But i configured app right. It's yii\mongodb\console\controllers\MigrateController' in config, but I have this error when i try to migrate.
