### ISSUE TITLE
ActiveRecord setIsNewRecord(true)  //Invalid

### ISSUE THREAD

**Issue by aklivecai** [yiisoft/yii2-mongodb#43]
>  yii\mongodb\ActiveRecord 
>  setIsNewRecord(true) 
> save() // Can't get the right result

``` php
$model =  Product::findOne($id);
$model->setIsNewRecord(true);
$model->save();
```

## Error Info
Exception (MongoDB Exception) 'yii\mongodb\Exception' with message '127.0.0.1:27017: E11000 duplicate key error index: mis.product.$_id_ dup key: { : ObjectId('55dafe868ead0e14170041a7') }

## Change code, can be normal operation
```php 
use yii\mongodb\ActiveRecord;

class Product extends ActiveRecord {
    //add   
    public function setIsNewRecord($value) {
        parent::setIsNewRecord($value);
       $this->_id = new \MongoId();
    }
   ...
}
```

**Comment by klimov-paul** [comment]
You should unset `_id` manually. This is the same behavior, which applies for normal `yii\db\ActiveRecord` with autoincremental primary key.
