### ISSUE TITLE
Class 'MongoClient' not found

### ISSUE THREAD

**Issue by farazsahebdel** [yiisoft/yii2-mongodb#48]
Hi

$connection = new \yii\mongodb\Connection([
    'dsn' => 'mongodb://localhost:27017 ',
]);
$connection->open();

error Class 'MongoClient' not found

**Comment by cebe** [comment]
looks like you have not installed the required php extension: https://github.com/yiisoft/yii2-mongodb/blob/master/composer.json#L22

**Comment by farazsahebdel** [comment]
installed extension mongodb in php
and has yii2-mongodb in vendor/yiisoft/

**Comment by cebe** [comment]
Could be that it is installed in console but not for web.

**Comment by farazsahebdel** [comment]
sorry
I did not catch

**Comment by samdark** [comment]
Often console uses different `php.ini` than web. Check `phpinfo()` for mongo.

**Comment by farazsahebdel** [comment]
in command :  php -m | grep mongo
result => mongo
