### ISSUE TITLE
Eager loading doesn't work for related data, lazy - does

### ISSUE THREAD

**Issue by Lisio** [yiisoft/yii2-mongodb#51]
What could be the misconfiguration of hasMany relation, if it works only with lazy loading?

SomeObject model has relation declared as following:
```php
public function getImages()
{
    return $this->hasMany(Image::className(), ['metadata.obj_id' => '_id']);
}
```

Code in controller:
```php
$data = SomeObject::find()->with('images')->where(['state' => 'active'])->one();
var_dump($data->images); // Array ( )
$data = SomeObject::find()->where(['state' => 'active'])->one();
var_dump($data->images); // Array ( [0] => app\models\Image Object ( and so on
```

**Comment by Lisio** [comment]
The roots of the problem are going to getModelKey method of yii2\db\ActiveRelationTrait, where dots in field names break everything. At the same time, hasMany method doesn't provide another solution.

**Comment by Lisio** [comment]
[Pull request](https://github.com/yiisoft/yii2-mongodb/pull/52)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-mongodb/issues/51

**Comment by samdark** [comment]
@Lisio what's the reason pull request was closed?

**Comment by Lisio** [comment]
It was replaced with pull request #53, where I removed unnecessary brackets.

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2/issues/11489
