### ISSUE TITLE
MongoDbTarget:61 

### ISSUE THREAD

**Issue by glstas** [yiisoft/yii2-mongodb#55]
var_export does not handle circular references in D:\OpenServer523\domains\OsTest\vendor\yiisoft\yii2\helpers\BaseVarDumper.php on line 187

 protected 'message' => string 'Serialization of 'Closure' is not allowed' (length=41)
  private 'string' => string '' (length=0)
  protected 'code' => int 0
  protected 'file' => string '\vendor\yiisoft\yii2\helpers\BaseVarDumper.php' (length=77)
  protected 'line' => int 183
  private 'trace' => 
    array (size=8)
      0 => 
        array (size=4)
          'file' => string '\vendor\yiisoft\yii2\helpers\BaseVarDumper.php' (length=77)
          'line' => int 183
          'function' => string 'serialize' (length=9)
          'args' => 
            array (size=1)
              0 => 
                &object(Exception)[75]
      1 => 
        array (size=6)
          'file' => string '\vendor\yiisoft\yii2\helpers\BaseVarDumper.php' (length=77)
          'line' => int 147
          'function' => string 'exportInternal' (length=14)
          'class' => string 'yii\helpers\BaseVarDumper' (length=25)
          'type' => string '::' (length=2)
          'args' => 
            array (size=2)
              0 => 
                &object(Exception)[75]
              1 => &int 0
      2 => 
        array (size=6)
          'file' => string '\vendor\yiisoft\yii2-mongodb\log\MongoDbTarget.php' (length=81)
          'line' => int 61
          'function' => string 'export' (length=6)
          'class' => string 'yii\helpers\BaseVarDumper' (length=25)
          'type' => string '::' (length=2)
          'args' => 
            array (size=1)
              0 => 
                &object(Exception)[75]

**Comment by glstas** [comment]
Look in yii\log\Target->formatMessage($message):240

if (!is_string($text)) {
            // exceptions may not be serializable if in the call stack somewhere is a Closure
            if ($text instanceof \Exception) {
                $text = (string) $text;
            } else {
                $text = VarDumper::export($text);
            }
        }

**Comment by klimov-paul** [comment]
Resolved by commit dd7ab0d4694bffd26ee333a2f698858096c157c1
