### ISSUE TITLE
is there is any way to store translations on mongo?

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-mongodb#57]
I want to use mongo for store the translations, but there is no class like yii\i18n\MongoMessageSource

**Comment by samdark** [comment]
Not yet.

**Comment by samdark** [comment]
You can implement it by extending from `MessageSource` and implementing `loadMessages` method.

**Comment by klimov-paul** [comment]
Issure resolved by commit 766f24dd89125c23fac31224634b8629630f9660

**Comment by demircancelebi** [comment]
Hi,
I am not a PHP guy and did not fully understood your code here, but as far as I understand you are storing translations in mongodb, I wonder how you overcome storing "." character in keys.
