### ISSUE TITLE
mongo ID

### ISSUE THREAD

**Issue by gb5256** [yiisoft/yii2-mongodb#58]
Hi, 
I am having problems when doing a find on MongoID.
       
     $query = new Query;
        $row = $query->from('item')
            where(['_id' => '564c75d0036421960286875f' ]) // implicit typecast to [[\MongoId]]
            ->one();

the query it produces looks like this:

    "query":{"_id":{"$id":"564c75d0036421960286875f"}}

Which produces an error as $id is not valid. It should look like this:

{ "_id": ObjectId("564c75d00364219602868749") }

Or am I doing someting wrong?

**Comment by crazyfd** [comment]
$query = new Query;
$row = $query->from('item')
        ->where(['_id' => new \MongoId('564c75d0036421960286875f')]) 
        ->one();
