### ISSUE TITLE
gii integration - model generator

### ISSUE THREAD

**Issue by xiandalisay** [yiisoft/yii2-mongodb#6]
I integrated the gii into the console/config/main-local.php.
The gii interface didn't changed. 

After clicking the preview, the following errors occured:
the table name does not exists; 
and, no application component database connection id

![capture](https://cloud.githubusercontent.com/assets/7392803/6778495/fc7c9c68-d18d-11e4-8644-6158cf5b44aa.PNG)

![capture](https://cloud.githubusercontent.com/assets/7392803/6778527/4c2211c6-d18e-11e4-88d2-c0d6e24c00cb.PNG)

![capture](https://cloud.githubusercontent.com/assets/7392803/6778534/5e30b71e-d18e-11e4-8947-1071929698e0.PNG)

**Comment by klimov-paul** [comment]
It is obvious you have accessed wrong generator: the one for regular 'DB'.
Choose generator carefully, there should extra 'MongoDB model' appear.
