### ISSUE TITLE
Mongodb and yii2 timestamp behaviour

### ISSUE THREAD

**Issue by miradnan** [yiisoft/yii2-mongodb#62]
I'm having issues with mongodb and yii's default yii\behaviors\TimestampBehavior. It does not support mongodb like timestamps. It throws an error. See below,

<h5>Code</h5>
<pre>
public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => new \MongoDate(),
            ],
        ];
    }
</pre>

<h5>PHP Warning </h5>'yii\base\ErrorException' with message 'call_user_func() expects parameter 1 to be a valid callback, no array or string given' .
Thats because MongoDate() would return an object by default.
Can't find anything on Google too on this issue. Any fixes?

**Comment by cebe** [comment]
```php
public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => function() { return new \MongoDate(); },
            ],
        ];
    }
```
