### ISSUE TITLE
Unknown component ID: db in  debug toolbar

### ISSUE THREAD

**Issue by devypt** [yiisoft/yii2-mongodb#63]
<img width="804" alt="screen shot 2015-12-13 at 8 18 41 pm" src="https://cloud.githubusercontent.com/assets/105605/11767924/c58ae952-a1d6-11e5-9e08-de40635d2aeb.png">

```

 'components' => [
        'assetManager' => [
            'class' => 'yii\web\AssetManager',
            'hashCallback' => function ($path) {
                return hash('md4', $path);
            },

        ],
        'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://' . DB_HOST . ':27017/testdb',

        ],

```

```


  $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        'panels' => [
            'mongodb' => [
                'class' => 'yii\\mongodb\\debug\\MongoDbPanel',
            ],
        ],
        'allowedIPs' => ['*']

    ];
```

**Comment by SilverFire** [comment]
`DbPanel` is enabled by default ([src](https://github.com/yiisoft/yii2-debug/blob/master/Module.php#L253)), by you do not have a `db` component, so you are getting the error.

Try the following

```php
 $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        'panels' => [
            'db' => [
                'class' => 'yii\\mongodb\\debug\\MongoDbPanel',
                'db' => 'mongodb',
            ],
        ],
        'allowedIPs' => ['*']
];
```

**Comment by devypt** [comment]
Thank. @SilverFire can we add this note to the debug section@ mongo db repo, i believe many user will use mongodb as their main db so they all will need this config.

**Comment by resurtm** [comment]
Personally to me it's obvious you should have change component ID or adjust DbPanel configuration entry. I see no reason to add this to docs.

**Comment by SilverFire** [comment]
Yes, it's obvious, but it might be added. Not a big deal https://github.com/yiisoft/yii2-mongodb/commit/dc2e810a23bd959ad42089e46e8640376f6a4303
