### ISSUE TITLE
Inserts are slow

### ISSUE THREAD

**Issue by adamwinn** [yiisoft/yii2-mongodb#65]
I've noticed inserting a document is quite slow using Yii2.  I compared Yii2 to a standard PHP Mongo code snippet and below are my findings and code.  Is there a reason why it's quite a bit slower in Yii?

Without Yii.  Takes 2.5 secs.
```php
        $connection = new \MongoClient(<dsn>);
        $collection = $connection->db->agreement;
        $doc = ["AgreementID" => "123"];
        $time_start = microtime(true);      
        $collection->insert( $doc );
        $time_end = microtime(true);
        $time = $time_end - $time_start;
        echo 'insert took '.$time;
```

With Yii.  Takes 13 secs.
```php
        $model = new Agreement;
        $model->AgreementID = '123';
        $time_start = microtime(true);
        $model->save();
        $time_end = microtime(true);
        $time = $time_end - $time_start;
        echo 'insert took '.$time;
```

**Comment by cebe** [comment]
> Without Yii. Takes 2.5 secs.

this sounds already really slow, are you sure you don't have networking issues or simliar problem in your environment?

**Comment by gallexme** [comment]
@adamwinn  u sure that its not 2.5ms?

**Comment by adamwinn** [comment]
My Mongo server is on AWS in the East region.  I ssh'd into a server in the East and ran:

```javascript
var before = new Date(); 
db.agreement.insert({"AgreementID":"123"}); 
var after = new Date(); 
execution_mills = after - before;
```
and it outputted around 50 each time.  So running a direct query from the command line is taking around 50ms.

The issue is if I run a simple mongo insert using Yii, It's taking 11-13 secs (This is also from a web server in the East region). 

I take it you guys aren't seeing that?  A mongo insert happens instantaneously for you?

**Comment by samdark** [comment]
Yes.

**Comment by SilverFire** [comment]
Could you try to insert a document from the server where Yii is running omitting Yii?

**Comment by adamwinn** [comment]
I ran another test on the webserver in the East region that's running Yii.  There should be no network latency or anything like that since the webserver and the MongoDB server are both in the East region.  I ran the same 2 inserts as in my first post.  One normal php mongo insert and one yii insert.

The results:
```javascript
normal mongo insert took 0.0010299682617188 secs
yii mongo insert took 10.2576379776 secs
```

**Comment by adamwinn** [comment]
I figured it out. If I turn off validation, it takes .01 secs.  I have a lot of fields so I guess validation was taking a while.  Thanks for the help!

**Comment by SilverFire** [comment]
It's not OK anyway. Could you show your validation rules?

**Comment by adamwinn** [comment]
I have 1,299 fields to validate against, so I'm guess that's why it took a while.

**Comment by SilverFire** [comment]
Wow :dizzy_face:
I hope it might be optimized somehow.

**Comment by samdark** [comment]
It's extremely rare use case and I guess one of rules is `exists`.

**Comment by SilverFire** [comment]
I'm afraid that all 1,299 fields are validated with `exists`

**Comment by zinzinday** [comment]
Core i-5 8G RAM localhost :(

![screenshot from 2015-12-19 01 02 13](https://cloud.githubusercontent.com/assets/441560/11903495/326e5568-a5ec-11e5-8c63-a8711082706c.png)

**Comment by samdark** [comment]
Hmm... 9 queries. @SilverFire our theory is wrong.

**Comment by samdark** [comment]
@zinzinday could you go to debug panel and see what's there for MongoDB?

**Comment by zinzinday** [comment]
I'll edit with pix of screen later bcos i'm going out. this work with search related title
Collection createIndex(['title'=>'text'])
and $query of DataProvider
Model::find()->select(['score' => ['$meta' => 'textScore']])
            ->where(['$text' => ['$search' => $query, '$language' => 'english']])
            ->orderBy(['score' => ['$meta' => 'textScore']]);

**Comment by yoyhosoft** [comment]
I ever found this problem also, the root course is your validate field isn't index key.
For my code I validate by using filed 'sku' as unique.

before I do index key, insert time is about 10-15 rows / seconds (collection total rows about 150K)
after I do index key, insert time is about 200-400 rows / seconds (collection total rows more than 2M)
