### ISSUE TITLE
Full text search has changed

### ISSUE THREAD

**Issue by knut** [yiisoft/yii2-mongodb#8]
[CollectionTest::testFullTextSearch()](https://github.com/yiisoft/yii2-mongodb/blob/b9afb2180a203fc320fe68de830929dbe490c030/tests/CollectionTest.php#L418) is failing with MongoDB 3.0.

It looks like the [`text` command](http://docs.mongodb.org/manual/reference/command/text/) that was added in MongoDB 2.4 for full text search was deprecated already in 2.6 in favor of the [`$text` operator](http://docs.mongodb.org/manual/reference/operator/query/text/#op._S_text).

In 3.0 you do the full text search like:
```
$collection->find(['$text' => [ '$search' => 'some text']]);
```

I see two options to solve this issue:

1. Let the `Collection::fullTextSearch()` choose how to query based on server version.

2. Mark [Collection::fullTextSearch](https://github.com/yiisoft/yii2-mongodb/blob/3204fbb3880754bd3f47df03b4154864bc632594/Collection.php#L700) as deprecated from 2.6 and refer to the [Collection::find()](https://github.com/yiisoft/yii2-mongodb/blob/b9afb2180a203fc320fe68de830929dbe490c030/Collection.php#L321) command.

**Comment by samdark** [comment]
I think solution 1 is more appropriate for now.

**Comment by samdark** [comment]
Both solutions are OK. I tend to choose second one myself.

**Comment by klimov-paul** [comment]
> Let the Collection::fullTextSearch() choose how to query based on server version.

That is unlikely to be possible, sinse 'text' command allows specification of the options, which have not match in '$text' condition.

> Mark Collection::fullTextSearch as deprecated from 2.6 and refer to the Collection::find() command.

Version of the MongoDB server and version of the PHP extension are different matters. We can not just mark this method deprecated as someone may still use it with the old server version.

**Comment by samdark** [comment]
Marking it as deprecated with `@deprecated` doesn't technically make it impossible to use old version. It's just IDEs that will display it differently.

**Comment by klimov-paul** [comment]
`Collection::fullTextSearch()` removed at 2.1
