### ISSUE TITLE
Composer require wrong in PHP 7 - Centos

### ISSUE THREAD

**Issue by conghai** [yiisoft/yii2-mongodb#81]
I have just install **PHP 7 & Mongo 3.2** on Cent os.
- Yii2-mongodb require: **"ext-mongo": ">=1.5.0"** (in composer.json). But PHP 7 don't has ext-mongo any more, It's change to **mongodb** and current stable version is **1.1.2**

```code
> composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-mongodb 2.0.4 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.3 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.2 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.1 requires ext-mongo >=1.4.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.0 requires ext-mongo >=1.3.0 -> the requested PHP extension mongo is missing from your system.
    - Installation request for yiisoft/yii2-mongodb ~2.0 -> satisfiable by yiisoft/yii2-mongodb[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
```
See here: 
- [https://github.com/mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library)
- [https://docs.mongodb.org/ecosystem/drivers/php/](https://docs.mongodb.org/ecosystem/drivers/php/)
![Image of PHP Dirver support](http://i.imgur.com/GBm4LWF.png)

**Install Old mongo with PHP 7 (it's error)**
```code
> pecl install mongo

WARNING: "pecl/mongo" is deprecated in favor of "channel:///mongodb"
pecl/mongo requires PHP (version >= 5.3.0, version <= 5.99.99), installed version is 7.0.2
No valid packages found
install failed
```

**Install New Mongo with PHP7**
```code
> pecl install mongodb

downloading mongodb-1.1.2.tgz ...
Starting to download mongodb-1.1.2.tgz (642,582 bytes)
...................done: 642,582 bytes
...
Build process completed successfully
Installing '/usr/lib64/php/modules/mongodb.so'
install ok: channel://pecl.php.net/mongodb-1.1.2
configuration option "php_ini" is not set to php.ini location
You should add "extension=mongodb.so" to php.ini
```

Somebody have solutions for it ?
Thank you.

**Comment by nigelterry** [comment]
See this thread https://github.com/yiisoft/yii2-mongodb/issues/56. 

My experience is that the mongofill solution works well. You will need to add:

        "mongofill/mongofill": "dev-master"

to composer.json and then update with 

composer update --ignore-platform-reqs

I hope we will get an updated MongoDB based version soon, but until then mongofill should get you working.

**Comment by klimov-paul** [comment]
Duplicates #56

**Comment by blackandcold** [comment]
I can approve that this is the same problem in Arch Linux for all those lost trying to fix it with symlinking the php.ini that is not anymore the problem!
