### ISSUE TITLE
Activerecord beforeSave not work.

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2-mongodb#83]
When set a new data in beforeSave event in model, the save() method return false and document not saved!

for example:

```php
if ($insert)
{
    $this->name = 'test';
}
```

**Comment by cebe** [comment]
please show the complete implementation of beforeSave()

**Comment by jafaripur** [comment]
Sorry this my fault in using of beforeSave() event in activerecord. It's Work.
