### ISSUE TITLE
Query subfield _id 

### ISSUE THREAD

**Issue by deplop** [yiisoft/yii2-mongodb#85]
I have a document like this in the db
I have tried some ways but I cannot query "category._id" like this:
Post::find()->where(["category._id" => "566625a4a84fb072f74b7072"])->all();

though the below query is possible 
Post::find()->where(["_id" => "566e883fc38b63a4038b4660"])->one(); 

{ "_id" : ObjectId("566e883fc38b63a4038b4660"),
 "category" : { 
            "_id" : ObjectId("566625a4a84fb072f74b7072"), 
            "name" : "ABC" 
      } 
}

The question is does Yii2 mongodb support the former query?

**Comment by klimov-paul** [comment]
You should typecast value of "category._id" to `MongoID` manually.

**Comment by deplop** [comment]
@klimov-paul 
I have searched on google and it seems you are right. But the problem is in the new php MongoDB driver ( http://php.net/manual/en/set.mongodb.php ), there are no MongoID class, as I know. What should I do.

**Comment by deplop** [comment]
I figured out that the new php MongoDB has \MongoDB\BSON\ObjectID class instead. 
Problem solved. Thanh you very much.
