### ISSUE TITLE
This extension will automatically close the cursor？

### ISSUE THREAD

**Issue by smartyPHP** [yiisoft/yii2-mongodb#88]
when i use this extension query something，and these query finish but Many  cursor is still exist，how to solve this problem?

**Comment by klimov-paul** [comment]
> Many cursor is still exist

What does this mean exactly? How did you determined that?

**Comment by smartyPHP** [comment]
do the cursor close automatically? Why I see a lot of cursors still exist after finishing query @klimov-paul

**Comment by klimov-paul** [comment]
> I see a lot of cursors still exist after finishing query

Where do you see them? How I can verify this?

**Comment by klimov-paul** [comment]
Closed, unless more information provided
