### ISSUE TITLE
how to do group by in mongodb

### ISSUE THREAD

**Issue by pavel-redkin** [yiisoft/yii2-mongodb#90]
Hi, everybody.
I have property (item.alias) I need to group by "alias"

```
class SearchHelper extends Object
{
    const PAGE_SIZE = 20;
    public function buildQuery()
    {
        $query = Item::find()
            ->where(['like', 'name', $this->q])
            ->orWhere(['like', 'vendor', $this->q])
            ->andWhere(['publish' => Item::PUBLISHED]);
        return $query;
    }

    public function buildDataProvider()
    {
        $query = $this->buildQuery();
        $data = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);
        return $data;
    }
}
```

I only come across  http://www.yiiframework.com/doc-2.0/yii-mongodb-collection.html#group()-detail
I have no idea to combine with ActiveQuery ( Item::find() )

**Comment by klimov-paul** [comment]
@pavel-redkin, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
