### ISSUE TITLE
support mongodb php driver - change to ext-mongo >=1.1.4

### ISSUE THREAD

**Issue by Venu85** [yiisoft/yii2-mongodb#91]
Can we change the required exension version to >=1.1.4
Because now the php extension changed from mongo to mongodb to support the latest PHP version.
Below is the error I see with docker
<code>Problem 1
    - yiisoft/yii2-mongodb 2.0.4 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.3 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.2 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.1 requires ext-mongo >=1.4.0 -> the requested PHP extension mongo is missing from your system.
    - yiisoft/yii2-mongodb 2.0.0 requires ext-mongo >=1.3.0 -> the requested PHP extension mongo is missing from your system.
    - Installation request for yiisoft/yii2-mongodb ~2.0.0 -> satisfiable by yiisoft/yii2-mongodb[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].</code>

**Comment by SilverFire** [comment]
Doplicates https://github.com/yiisoft/yii2-mongodb/issues/56?
