### ISSUE TITLE
There isn't tableName in ActiveRecorder class, how can I handle many table in one model, I want via one model User to save data in  user_1,user_2, user_3...

### ISSUE THREAD

**Issue by xiaomalover** [yiisoft/yii2-mongodb#95]
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by klimov-paul** [comment]
@xiaomalover, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
