### ISSUE TITLE
Displaying, Sorting and Filtering Model Relations 

### ISSUE THREAD

**Issue by nibinpaul** [yiisoft/yii2-mongodb#98]
i want to filter data with related data like in [http://www.yiiframework.com/wiki/653/displaying-sorting-and-filtering-model-relations-on-a-gridview/](url).
when i tried the above url it shows error Calling unknown method: yii\mongodb\ActiveQuery::joinWith()

how i can filter data with related data using ActiveDataProvider.

please help me..

**Comment by klimov-paul** [comment]
@nibinpaul, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
