### ISSUE TITLE
Cannot disable select fields (_id) in mongo db query

### ISSUE THREAD

**Issue by giannisdag** [yiisoft/yii2-mongodb#99]
In the documentation of mongo/db/query is written

>  the fields of the results to return. For example: `['name', 'group_id']`, `['name' => true, '_id' => false]`.
>      * Unless directly excluded, the "_id" field is always returned. If not set, it means selecting all columns

### What steps will reproduce the problem?
So to reproduce the problem we can make a query like the following
`$mongoQuery->select(['user_sportid'],['_id' => false])->from('player');`
### What's expected?
and we should expect to get only the user_sportid not the _id of the record
### What do you get instead?
Instead I am getting both of them, user_sportid and _id

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.7
| PHP version      | 5.6
| Operating system | ubuntu 14.0.4
mongodb 2.6

**Comment by klimov-paul** [comment]
Duplicates https://github.com/yiisoft/yii2/issues/7010
